### ISSUE TITLE
Does Ane Include in Ane Club?

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/Admob-ANE#1]
Does Ane Include in Ane Club?

**Comment by myflashlab** [comment]
Yes, sure it does, it must be in package V18. Please login to your panel
and download V18.

On Monday, June 6, 2016, Gamezhero <notifications@github.com> wrote:

> Does Ane Include in Ane Club?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/myflashlab/Admob-ANE/issues/1>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFKBVbIeIBKPd_GWHoBG_T27f1dIfks5qJEQQgaJpZM4IvDMd>
> .
>


-- 
Sent from iPhone

**Comment by Gamezhero** [comment]
ok I see 17 only - waiting
