### ISSUE TITLE
ad is not displayed on Android

### ISSUE THREAD

**Issue by pol2095** [myflashlab/Admob-ANE#11]
Hello,

I try the demo AdMob ane but the ad is not displayed on Android

I have only this message : "ANE DEMO VERSION you are using a demo version of this extension! www.myFlashLabs.com"

-
what is the "AdMob ApplicationCode" in
```javascript
AdMob.init(stage, "ca-app-pub-9002001127208746~3709582175");
```
is-it necessary for the demo version ?

Thanks

**Comment by myflashlab** [comment]
Of course it is! Make sure you are reading the documentation first to know how you should work with the ANE. https://github.com/myflashlab/Admob-ANE/wiki thanks. If you are facing an error message or anything, do feel free to open a new issue.
