### ISSUE TITLE
zip Download failed from Club membership

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/Admob-ANE#12]
![screen shot 2016-11-30 at 3 34 12 pm](https://cloud.githubusercontent.com/assets/7042361/20770092/7b3c4a56-b712-11e6-8432-842ba6a4fe8c.png)
I sent a couple of emails and never got a response, I purchased the Club membership and when I tried to download the zip file 34MB, it crashes at 13%, tried 5 times and now it says I have reached the maximum downloads, what can I do after paying $149 and got no files... :(

**Comment by imalitavakoli** [comment]
Maybe there was a problem in your internet connection at that moment. Though there are no worries, our teammate got back to you in less than 4 hours! And of course be with you till you receive the files successfully. Nothing to be worry about. Cheers.
