### ISSUE TITLE
Starling Project, screen "stage" ?

### ISSUE THREAD

**Issue by pumazoom** [myflashlab/Admob-ANE#13]
Hi.

I got an error when adding "AdMob.init(stage, "ca-app-pub-..............................");

1067: Implicit coercion of a value of type starling.display:Stage to an unrelated type flash.display:Stage.

What i have to use to replace "stage" please?
Regards

**Comment by myflashlab** [comment]
You are sending the Starling Stage reference to the ANE which is wrong. instead you must send the Flash Stage ```flash.display.Stage```. You should be able to do that easily. check this page: http://forum.starling-framework.org/topic/get-access-to-main-flashstage-from-a-starling-display-object

**Comment by pumazoom** [comment]
Thank you.

After adding "Starling.current.nativeStage" for "stage"..
I got this this error : 
ArgumentError: Error #3500: The extension context does not have a method with the name command.

I work on Flash CC

**Comment by myflashlab** [comment]
Well, this error message means that the ANE is not correctly embedded in your project OR you are trying to run on a simulator? if so, try running on a real device. You might also find the information on this video screencasts helpful: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by ionutmihaila** [comment]
Hi guys,

Same problem here. I've followed the documentation correctly:
- updated the XML
- copied in lib/aot/stub folder all frameworks
- added all dependent ANEs 

There is no conflict with any other ANE, however I get the same error "**ArgumentError: Error #3500: The extension context does...**", in both Flash CC or a real device. So it gets stuck at this line:

AdMob.init(stage, "ca-app-pub-11111111111111111");

Please help! 
Many thanks!

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
