### ISSUE TITLE
Can I generate "idfa" with Admob?

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/Admob-ANE#14]
Question: Can I generate "idfa" with Admob? 

FYI: https://developers.google.com/app-conversion-tracking/ios/conversion-tracking-server

That ADVERTISING IDENTIFIER will be used for AdWords? 

If yes, is it available on both iOS and Android?

Thanks,

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
