### ISSUE TITLE
How to add app ID?

### ISSUE THREAD

**Issue by replayshot** [myflashlab/Admob-ANE#16]
When I read instructions for adding AdMob without ANE (on this page: https://firebase.google.com/docs/admob/android/quick-start ), it has a mention of App ID as follows: MobileAds.initialize(getApplicationContext(), "ca-app-pub-3940256099942544~3347511713");

Since they mention it, I assume, this is needed for some features within AdMob, but when using your Admob-ANE I don't see this App ID mentioned in any documentation, so how do I add it?

Note, APP ID is different then AD ID.

Thank you in advance for your help.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
