### ISSUE TITLE
Error Buid Ane Admob with com.freshplanet.AirGooglePlayGamesService

### ISSUE THREAD

**Issue by kyoshyro86** [myflashlab/Admob-ANE#17]
Hi MyFlashLabs.
 I have Error when compile your admob ane with freshplanet.AirGooglePlayGamesService. How can i do? :( (Have You only admob ane not include googleplayservice?)
Thanks and Best Regard

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
