### ISSUE TITLE
Banner didn't show on iOS 9

### ISSUE THREAD

**Issue by betenner** [myflashlab/Admob-ANE#23]
I have implemented your ANE just as your example code.
The interstitial ad showed correctly.
But the banner didn't show at all.
The onAdLoaded event is fired correctly and I tried changing the x and y of the banner but didn't work.
Any other possible reason to cause this?

**Comment by myflashlab** [comment]
Watch out for the logs in xcode or Android Studio. The logs should be able to tell you what could be wrong. And by the way, make sure to use ```ApiBannerAds.BANNER``` for your first test.

**Comment by myflashlab** [comment]
please let us know if you have more information on this?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
