### ISSUE TITLE
Witch parameter do you use for getting Andoid ID?

### ISSUE THREAD

**Issue by misterPitty** [myflashlab/Admob-ANE#24]
Hi again. I use Android Studio to get Andoid ID as you recommend but parameter _Settings.Secure.ANDROID_ID_ return only 16-symbols string.
As i know i need 32-symbols string to add it in test devices array. Am i right?
So which parameter or function do you use for getting this ID. Thanks.

**Comment by myflashlab** [comment]
> The Mobile Ads SDK uses the tag "Ads" when writing to logcat. In Android Studio's logcat viewer, you can filter for that tag when you View the system log. This makes it easier to find your device's ID.

https://developers.google.com/admob/android/targeting#test_ads

you mean the device request ID, right?

**Comment by misterPitty** [comment]
From this linc:
> Set up test ads by passing your hashed Device ID to AdRequest.Builder.addTestDevice():
I can't understand where can i know this hashed Device ID.

**Comment by myflashlab** [comment]
Ok, so, I did understood your question correctly, as the google doc says:

> The Mobile Ads SDK uses the tag "Ads" when writing to logcat. In Android Studio's logcat viewer, you can filter for that tag when you View the system log. This makes it easier to find your device's ID.

https://developers.google.com/admob/android/targeting#test_ads

**Comment by misterPitty** [comment]
Your method isn't work in my case, but i find the way. _For other developers - https://play.google.com/store/apps/details?id=pe.go_com.admobdeviceidfinder&hl=en_
Anyone thanks for the answers.

**Comment by myflashlab** [comment]
good find!
