### ISSUE TITLE
ArgumentError: Error #3500: The extension context does...

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/Admob-ANE#25]
Hi guys,

Can you please help with the same problem I have as this user raised here - [#13](https://github.com/myflashlab/Admob-ANE/issues/13)?
I've followed the documentation correctly:

- updated the XML
- copied in lib/aot/stub folder all frameworks
- added all dependent ANEs

There is no conflict with any other ANE, however I get the same error "**ArgumentError: Error #3500: The extension context does...**", in both Flash CC or a real device. I am using AIR 25, on Android.

So it gets stuck at this line:
**AdMob.init(stage, "ca-app-pub-11111111111111111");**

Please help!
Many thanks!

**Comment by ionutmihaila** [comment]
Any help with this one, please?

**Comment by myflashlab** [comment]
Whenever you see an error which says ```The extension context does not exists``` it means that the ANE has not been correctly packaged in your app. these videos you might find helpful: https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

**Comment by ionutmihaila** [comment]
Thank you! I've checked the video and followed the instructions (it's not the first ANE from you that I use).
Just installed the app in the Android emulator and here's what the logcat says:

```
06-22 20:27:14.049 D/AdmobANE( 6718): AirCommand|||initialize started...
**06-22 20:27:14.065 E/GooglePlayServicesUtil( 6718): The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.**
06-22 20:27:14.154 W/System  ( 6718): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
06-22 20:27:14.303 D/DynamitePackage( 6718): Instantiated singleton DynamitePackage.
06-22 20:27:14.303 D/DynamitePackage( 6718): Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
06-22 20:27:14.577 D/AdmobANE( 6718): AirCommand|||initialize finished
06-22 20:27:14.577 D/AdmobANE( 6718): AirCommand|||setting layers started...
06-22 20:27:14.578 D/AdmobANE( 6718): AirCommand|||setting layers finished
06-22 20:27:14.581 W/art     ( 6718): Long monitor contention event with owner method=void java.lang.Thread.nativeCreate(java.lang.Thread, long, boolean) from Thread.java:429496729
4 waiters=2 for 145ms
**06-22 20:27:14.582 D/AdmobANE( 6718): AirCommand|||initInterstitial started...
06-22 20:27:14.582 W/ActivityManager( 1689): Unable to start service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending } U=0: not found
06-22 20:27:14.587 D/AdmobANE( 6718): AirCommand|||initInterstitial finished**
06-22 20:27:14.993 I/art     ( 6718): Background partial concurrent mark sweep GC freed 24767(2MB) AllocSpace objects, 3(164KB) LOS objects, 33% free, 7MB/11MB, paused 3.715ms tota
l 166.659ms
```

I've flagged the parts that seem to be related to Admob. 
Do you have any clue that might help me to understand where the problem is?

PS: I've added correctly all ANEs (androidSupport.ane V24.2.1, overrideAir.ane V4.0.0, googlePlayServices_adsLite.ane V10.2.0, googlePlayServices_basement.ane V10.2.0)

Many thanks!
Ionut

**Comment by ionutmihaila** [comment]
Found the bug :) InAppBillingService error remembered me I didn't set up the payment method in Admob, which seems like is mandatory... Thank you for your support, great ANE!
