### ISSUE TITLE
AdRequest public properties not working

### ISSUE THREAD

**Issue by ionutmihaila** [myflashlab/Admob-ANE#26]
Hi,

Can you please confirm if AdRequest's public properties are working?
For example, I've used the **keywords** property like this and doesn't seem to influence the ad type:

```
var adRequest:AdRequest = new AdRequest();
adRequest.keywords = ["chicken"];
```
I am using AIR25, on Android.

Thank you,
Ionut

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
