### ISSUE TITLE
issue for ios in animate cc

### ISSUE THREAD

**Issue by jabirraju** [myflashlab/Admob-ANE#27]
while the ane works for android i got following issue when compiled for ios.

Id: framework not found GoogleMobileAds

see shots for reference
<img width="960" alt="ios issue" src="https://user-images.githubusercontent.com/68838/28611747-6d506810-720a-11e7-9e30-7d92d72456e8.png">

**Comment by jabirraju** [comment]
i used these ane in the project fla.
<img width="960" alt="ane_used" src="https://user-images.githubusercontent.com/68838/28611824-bea8ad08-720a-11e7-9daf-3d14b5f318a9.png">

**Comment by myflashlab** [comment]
Check out here: https://github.com/myflashlab/Admob-ANE/wiki/A.-Preparing-the-Adobe-Air-side

> Make sure you have copied the iOS frameworks to "YOU_AIR_SDK\lib\aot\stub"

> To compile on iOS, you will need to add the GoogleMobileAds framework to your AIR SDK.

Admob ANE is synced with our Firebase collection. you can find the GoogleMobileAds framework here: https://dl.google.com/firebase/sdk/ios/4_0_3/Firebase-4.0.3.zip

**Comment by myflashlab** [comment]
Please let us know if you still have trouble with this?

**Comment by jabirraju** [comment]
Make sure you have copied the iOS frameworks to "YOU_AIR_SDK\lib\aot\stub"
[comment]: i copied the whole folder and then folder content in that dir then still i did not figured it.

**Comment by myflashlab** [comment]
<img width="1019" alt="screen shot 2017-08-16 at 6 19 35 pm" src="https://user-images.githubusercontent.com/1692948/29368008-9a3b9bf0-82af-11e7-8c21-c2d1834ebaed.png">

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
