### ISSUE TITLE
ane working on kindle fire tablets?

### ISSUE THREAD

**Issue by Seb-AS** [myflashlab/Admob-ANE#28]
Hi,

I tried several AdMob anes and I always have some issue with google play services.(using GSP library ane), and I was wondering if your ane works fine with kindle fire?

errors:
1 - W/GooglePlayServicesUtil: Google Play Store is missing.

2- W/PackageManager: com.android.vending is not installed for user 0

thanks

**Comment by myflashlab** [comment]
if google play store is missing, that might be a problem. haven't tested that though. But we are interested to try to make it work even if it doesn't! Please try the demo ane and tell us how it goes. If it doesn't work already, maybe we can somehow inject the required services inside it. 🤔

**Comment by Seb-AS** [comment]
Hi, tested it and AdMobEvents.AD_LOADED doesn't fire, https://github.com/myflashlab/Admob-ANE/issues/22

thanks

**Comment by myflashlab** [comment]
hmm, I'm not sure that can happen any longer. check this out: https://developers.google.com/admob/android/sdk

>> The Google Mobile Ads SDK for Android is now a part of the Google Play services platform. It is no longer available as a standalone SDK. 

Let me know if you can find a native solution that maybe we can mirror it in an ANE.

**Comment by joe7dust** [comment]
I'm trying to do "pm uninstall -k --user 0 com.amazon.kindle.kso" on my Fire 7 HD 5th gen running 5.4.0.1 to get rid of the lock screen ads, but it is telling me "Failure - not installed for 0"

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
