### ISSUE TITLE
how to check rewarded interstitial ads event

### ISSUE THREAD

**Issue by babakasol** [myflashlab/Admob-ANE#29]
Hi, 
I am using Admob-ANE for rewarded interstitial ads but how do i capture that the  user has seen the complete ad or not. I am using the admob events for capturing the adclosed event but it dosnt clears that the user has seen the complete ad if the user cancels the ad in between there is no such event for that.

Waiting for you response 
Thankyou in advance.

**Comment by myflashlab** [comment]
Well, the nearest event you can use is [AD_LEFT_APP](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/admob/events/AdMobEvents.html#AD_LEFT_APP) we are reflecting all the native events. if the native side does not have such an event, then the ANE does not have it neither.
