### ISSUE TITLE
flash.events.Event.DEACTIVATE activates on Android when show ads

### ISSUE THREAD

**Issue by Gamezhero** [myflashlab/Admob-ANE#3]
When I show interstitial ads on android I see activation flash.events.Event.DEACTIVATE event and flash.events.Event.ACTIVATE when back, I don't see it on iOs.

Can we make it how on iOs?

**Comment by myflashlab** [comment]
no, you can't. This is how iOS/Android views are different. to work with this, you should rely on the Admob events.

```actionscript
AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, 				onAdClosed);
AdMob.api.addEventListener(AdMobEvents.AD_FAILED, 				onAdFailed);
AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, 			onAdLeftApp);
AdMob.api.addEventListener(AdMobEvents.AD_LOADED, 				onAdLoaded);
AdMob.api.addEventListener(AdMobEvents.AD_OPENED, 				onAdOpened);
```
