### ISSUE TITLE
onAdLoaded succeeds, but no banner is visible

### ISSUE THREAD

**Issue by vincentvictoria** [myflashlab/Admob-ANE#30]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version:
* iOS Version: 9.3.5
* AIR SDK Version: 27

## Problem Description ##

I bought the ANE this week, and successfully integrated to Android and published it to Play Store.
Then now I'm trying on iOS.
I successfully built an iOS app: copying admob,firebase frameworks & configuring manifest, embedding other dependencies. Compiled it fine.
I installed it on iPad 3.
I launched it, but cannot see any ad.
onAdLoaded() is fired and the banner seems to be inside the screen (x:0, y:0, w:1536, h:one hundred something..), but the ad is not visible.
Admob.api.banner.visible is true.
onAdFailed() is not fired.

Do you know any causes?

**Comment by myflashlab** [comment]
it's probable that your ads are not displayed because of size problem. try ```ApiBannerAds.BANNER``` for example. Let's see some of you code anyway. so we can better help you.

**Comment by vincentvictoria** [comment]
I tried BANNER first and then SMART_BANNER but it doesn't seem to make any difference.
I don't resize nor reposition the ad.

**Initilization:**
// Add general listeners for the Ads
//AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, 				onAdClosed);
AdMob.api.addEventListener(AdMobEvents.AD_FAILED, 				onAdFailed);
//AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, 			onAdLeftApp);
AdMob.api.addEventListener(AdMobEvents.AD_LOADED, 				onAdLoaded);
//AdMob.api.addEventListener(AdMobEvents.AD_OPENED, 				onAdOpened);

// listen to the banner Ad to get its final width/height in pixels
//AdMob.api.banner.addEventListener(BannerEvents.SIZE_MEASURED, 	onBannerAdSizeReceived);

// to create a banner Ad, first you need to initialize a new banner with your unitId and prefered banner size
//AdMob.api.banner.init( adId, ApiBannerAds.BANNER);
AdMob.api.banner.init( adId, ApiBannerAds.SMART_BANNER_PORTRAIT);

// then you should create a new Ad request
var adRequest:AdRequest = new AdRequest();

// Now that you have the Ad request ready, simply load your banner! That simple.
var api:AdMobApi = AdMob.api;
api.banner.loadAd(adRequest);

**onAdLoaded**
private function onAdLoaded(e:AdMobEvents):void
{
trace( "[Main::onAdLoaded] "+e.toString() );
}

**Comment by vincentvictoria** [comment]
Exact size and location onAdLoaded is
x=0,y=0,w=1536,h=180

**Comment by myflashlab** [comment]
When initializing the ANE on the iOS side, have you considered this: https://github.com/myflashlab/Admob-ANE/blob/master/AIR/src/Demo.as#L94-L96

> C.log("iOS is crazy with understanding stageWidth and stageHeight, you already now that :)");
			C.log("So, we should wait a couple of seconds before initializing Admob to make sure the stage dimention is stable before passing it through the ANE.");
setTimeout(init, 4000);

**Comment by vincentvictoria** [comment]
1. I actually initialize ad after an user clicks a button, so I think it's not the stage dimension problem.
2. onBannerAdSizeReceived prints out
[Main::onBannerAdSizeReceived] w=1536,h=180

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
