### ISSUE TITLE
How to implement Google Adwords

### ISSUE THREAD

**Issue by SaleemEM** [myflashlab/Admob-ANE#32]
Hi Team,

I didn't find any ANE related Google Adwords, I found lot of Google ANE in "/MyFlashLabClub_ANEs_package/common-dependencies-ANE-master/googlePlayServices",

but don't know, is any one of them useful for Adwords implementation, we want to integrate Google Adwords in our Air project (Android and iOS), I'd appreciate if you please help us regarding this.

## Environment ##

* iOS Version: 11.2.0
* AIR SDK Version: Air 28

**Comment by myflashlab** [comment]
implement Google Adwords?! I'm confused because as far as I know, you use adwords to place your own ads on Google as channels. If you want to show ads, then Admob is the ANE you need. Let me know if I understood you correctly?
