### ISSUE TITLE
Question: Can a banner be placed as a child of a DisplayObject?

### ISSUE THREAD

**Issue by lucien144** [myflashlab/Admob-ANE#33]
I'd like to start displaying banners in my app inside a list, to be more specific inside a custom ItemRenderer. Is that possible? Following the docs I'm not sure if that's even possible... I'm looking for something like this: `item.addChild(banner);`

Thanks.

**Comment by myflashlab** [comment]
Native windows are on top of all AIR content and thinking about them as children of AIR display list is not correct. The best you can do is to change the admob object x/y location using its own ANE API to somehow simulate the addChild behavior.
