### ISSUE TITLE
onBannerAdSizeReceived fires, but get onAdFailed error code 3 and no banner ads show

### ISSUE THREAD

**Issue by jennycxu** [myflashlab/Admob-ANE#35]
## Environment ##
* Android API Version: N/A
* iOS Version: 7.29.0
* AIR SDK Version: 30.0.0.107

## Problem Description ##
For some reason, the banner ads always fail to load -- the interstitials are fine. The game is very up to date on all of the ANEs as well. I get the error code 3 when requesting ads. I have also enabled test devies. 

* Copy your manifest ```.xml``` file.
```xml
<image29x29>Icons/icon29.png</image29x29>
        <image57x57>Icons/icon57.png</image57x57>
        <image114x114>Icons/icon114.png</image114x114>
        <image512x512>Icons/icon_512x512.png</image512x512>
        <image48x48>Icons/icon_48x48.png</image48x48>
        <image72x72>Icons/icon72.png</image72x72>
        <image50x50>Icons/icon50.png</image50x50>
        <image58x58>Icons/icon58.png</image58x58>
        <image100x100>Icons/icon100.png</image100x100>
        <image144x144>Icons/icon_144x144.png</image144x144>
        <image40x40>Icons/icon40.png</image40x40>
        <image76x76>Icons/icon76.png</image76x76>
        <image80x80>Icons/icon80.png</image80x80>
        <image120x120>Icons/icon120.png</image120x120>
        <image152x152>Icons/icon152.png</image152x152>
        <image180x180>Icons/icon180.png</image180x180>
        <image60x60>Icons/icon60.png</image60x60>
        <image75x75>Icons/icon75.png</image75x75>
        <image87x87>Icons/icon87.png</image87x87>
        <image167x167>Icons/icon%20167.png</image167x167>
    </icon>
    <supportedLanguages>en zh cs da nl fr de iw it ja ko nb pl pt ru es sv tr</supportedLanguages>
    <versionLabel></versionLabel>
    <iPhone>
        <requestedDisplayResolution>high</requestedDisplayResolution>
        <InfoAdditions><![CDATA[
  <key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
  </dict>
  <key>NSCalendarsUsageDescription</key>
  <string>App would like to create a calendar event.</string>
  <key>ITSAppUsesNonExemptEncryption</key><false/>
  
  <key>UIDeviceFamily</key>
  <array><string>1</string><string>2</string></array>
  <key>MinimumOSVersion</key>
  <string>8.0</string>
]]></InfoAdditions>
    </iPhone>
    <extensions>
        <extensionID>com.jirbo.airadc.AirAdColony</extensionID>
        <extensionID>com.milkmangames.extensions.RateBox</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.analytics</extensionID>
        <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
        <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.milkmangames.extensions.GameCenter</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    </extensions>
</application>
```
* Copy your Actionscript code.
```actionscript
AdMob.api.banner.init(ADMOB_BANNER, ApiBannerAds.SMART_BANNER_LANDSCAPE);
			if(!AdMob.api.banner.hasEventListener(BannerEvents.SIZE_MEASURED))
				AdMob.api.banner.addEventListener(BannerEvents.SIZE_MEASURED, 	onBannerAdSizeReceived);
			var adRequest:AdRequest = getAdRequest();
			AdMob.api.banner.loadAd(adRequest);
```

## Steps to Reproduce ##
Open app

**Comment by jennycxu** [comment]
Thanks for the link and for the notice! I updated the Admob ANE to 3.0.0 but nothing changed -- the issue happens for me even when I have test ads though, which is confusing to me since I thought that they would not run out of ad inventory on test.  I also tried to do a BANNER request on an IPA I published and though that one showed up, when I publish a new APK without the BANNER request and instead a SMART_BANNER_LANDSCAPE the smart ads still don't show.  Thanks!

**Comment by myflashlab** [comment]
Do you have this problem on newer iOS versions? min iOS version that our ANEs support is iOS 8+.
Anyway, I'm kinda confused, you are having this problem on Android or iOS? in your last message you said ```APK```.

**Comment by jennycxu** [comment]
Oh sorry about that! I’m using iOS 11, slip of the fingers.

**Comment by myflashlab** [comment]
Ok, considering that you are seeing the error code 3, it generally means that your setup is fine. However you may try re-checking your unitIds and your applicationCode. You may also use sample unitIds found here: https://developers.google.com/admob/android/test-ads#sample_ad_units. Other things may have caused the errorCode 3 is that may be you are behind a firewall or a proxy or using VPNs? 

Anyhow, you may also try asking this question from Admob directly or in Stackoverflow because this is not something related to the ANE!

**Comment by jennycxu** [comment]
Okay thank you! Also, seems like the test ads all load now but non test ads don’t work at all? Wasn’t sure if that’s something that’ll fix itself once the game goes live on the App Store? Thanks!

**Comment by myflashlab** [comment]
Well, you need to make sure the real Ads work also. If test Ads work and real ones don't, means your app setup is fine but there might be something wrong in your Admob account or UnitIDs...

**Comment by jennycxu** [comment]
Nevermind, the banner ads started appearing after launching the app again! Seems like there's a period of time before the banners start filling. Thanks for the help!
