### ISSUE TITLE
Rewarded video ads not displaying for testing

### ISSUE THREAD

**Issue by dr-andy** [myflashlab/Admob-ANE#36]
## Environment ##
* Android API Version: -
* iOS Version: 9.3.5
* AIR SDK Version: 30

## Problem Description ##
I try your demo on an iPad and all ads work as expected, but only rewarded video ads do not display.
I used test ad unit as below (https://developers.google.com/admob/android/test-ads):
```
AdMob.api.rewardedVideo.loadAd(adRequest, "ca-app-pub-3940256099942544/5224354917");
```
I have also added my device ID to adRequest.testDevices.
```
onAdFailed errorCode > 9
onAdFailed msg > Error Domain=com.google.ads Code=9 "No ad returned from any ad server"

```

**Comment by ionutmihaila** [comment]
Same error here.. On IOS only.. 
Works fine on Android.. 

Please help!

Thank you,
Ionut

**Comment by myflashlab** [comment]
You need to play around with the unitId thing... This seems like a recent problem from Admob servers or something, I'm not sure but we have seen a few more new issues with the similar problem in the past few days. Anyhow, just re-check your application code strings and unitId strings and make sure they match.

Such problems are not related to how ANE works. These are returned from Admob servers and you may find better answers on stackoverflow.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
