### ISSUE TITLE
Admob is not working 

### ISSUE THREAD

**Issue by nikhilreddy123456** [myflashlab/Admob-ANE#37]
This is my coding
```actionscript
import com.myflashlab.air.extensions.admob.*;
import com.myflashlab.air.extensions.admob.events.*;
import com.myflashlab.air.extensions.admob.banner.*;
import com.myflashlab.air.extensions.dependency.*;
import flash.events.MouseEvent;


if(OverrideAir.isSupported)
{
	AdMob.init(stage, "ca-app-pub-9002001127208746~3709582175");
	trace("Android ")
}
else
{
	trace("ios")
}



			btn0.addEventListener(MouseEvent.CLICK, initBanner);
			btn1.addEventListener(MouseEvent.CLICK, interstitial);
			
			
			function interstitial(e:MouseEvent):void
             {
				 AdMob.api.interstitial.init("ca-app-pub-9476398060240162/1457820116");

			 }
             
			function initBanner(e:MouseEvent):void
			{
				
				AdMob.api.banner.init("ca-app-pub-45212548785225/215478996521", ApiBannerAds.BANNER); // unitId for Android
				trace("clicked")
				//AdMob.api.banner.init("ca-app-pub-45212548785225/215478893028", ApiBannerAds.BANNER); // unitId for iOS
			}
```

//---------------------------------------------.xml----------------------------------------------------

```xml
 <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
	
	<!--The new Permission thing on Android works ONLY if you are targetting Android SDK 23 or higher-->
	<uses-sdk android:targetSdkVersion="26"/>
	
	<application>
		
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		
		<!-- Include the AdActivity and InAppPurchaseActivity configChanges and themes. -->
        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />
			
		<meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
		
	</application>
</manifest>]]></manifestAdditions>
  </android>
  
 
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
  </extensions>
</application>

```

**Comment by myflashlab** [comment]
make sure you have upgraded to the latest version. as described in the [changelog](https://github.com/myflashlab/Admob-ANE#changelog) the AS packages are changed. so you should only use ```import com.myflashlab.air.extensions.admob.*;``` to import the ANE into your code. more over, check out the updated sample AS codes.

**Comment by nikhilreddy123456** [comment]
if i add Cloud Game saves in my file Admob is not working or file crashes. I am using Cloud save process from myflashlab.In JSON stringify i added total game play like (Sharedobj3) file itself getting crashes or not responding.

**Comment by nikhilreddy123456** [comment]
import flash.display.Bitmap;
import flash.display.BitmapData;
import flash.display.Loader;
import flash.display.Sprite;
import flash.events.Event;
import flash.events.IOErrorEvent;
import flash.events.StatusEvent;
import flash.filesystem.FileMode;
import flash.filesystem.FileStream;
import flash.net.URLRequest;
import flash.filesystem.File;
import flash.utils.ByteArray;

import com.myflashlab.air.extensions.gameServices.GameServices;
import com.myflashlab.air.extensions.gameServices.google.events.AuthEvents;
import com.myflashlab.air.extensions.gameServices.google.events.SnapshotsEvents;
import com.myflashlab.air.extensions.gameServices.google.snapshot.Snapshot;

import com.myflashlab.air.extensions.gameServices.google.snapshot.Conflict;
import com.myflashlab.air.extensions.gameServices.google.player.PlayerLevel;
import flash.text.TextField;
import flash.events.MouseEvent;
//==========================================var decl===========================================================================
var temp:Boolean=false;
panel.visible=false

//=========================================Notify=====================================================================
function notify(msg:String):void
{
        alertmsg.appendText(msg);
        alertmsg.appendText("\n");
}
//=========================================init=====================================================================

init()

function init():void
{
        
        GameServices.init(true); 
        GameServices.google.auth.addEventListener(AuthEvents.INIT, onInit);

}

function onInit(e:AuthEvents):void
{
        var result:String;

        switch (e.status) 
        {
                case GameServices.SUCCESS:
                        
                        result = "GameServices.SUCCESS";
                        onSuccessfullInit();
                   
                     
                break;
                case GameServices.SERVICE_MISSING:
                        
                        result = "GameServices.SERVICE_MISSING";
                        
                break;
                case GameServices.SERVICE_DISABLED:
                        
                        result = "GameServices.SERVICE_DISABLED";
                        
                break;
                case GameServices.SERVICE_INVALID:
                        
                        result = "GameServices.SERVICE_INVALID";
                        
                break;
                default:
        }
        
        notify("onInit result = " + result);
}

//=========================================onSuccessfullInit =====================================================================
function onSuccessfullInit():void
{
        GameServices.google.auth.addEventListener(AuthEvents.TRYING_SILENT_LOGIN,                 onSilentTry);
        GameServices.google.auth.addEventListener(AuthEvents.LOGIN,                                         onLoginSuccess);
        GameServices.google.auth.addEventListener(AuthEvents.ERROR,                                         onLoginError);
        login()
        function login():void
        {
                GameServices.google.auth.login();
                
        }

}

function onSilentTry(e:AuthEvents):void
{
        notify("canDoSilentLogin = "+ e.canDoSilentLogin);
        if (e.canDoSilentLogin)
        {
                notify("connecting to Game Services, please wait...");
        }
}

var man:String;
function onLoginSuccess(e:AuthEvents):void
{
        temp=true;
        
        notify("---------------- onLoginSuccess");
        notify("displayName = " +                                 e.player.displayName);
        notify("id = " +                                                 e.player.id);
        man=e.player.id
        if (e.player.lastLevelUpTimestamp)  
        {
                notify("lastLevelUpTimestamp = " +         e.player.lastLevelUpTimestamp.toLocaleString());
        }
        notify("title = " +                                                 e.player.title);
        notify("xp = " +                                                 e.player.xp);
        var currLevel:PlayerLevel = e.player.currentLevel;
        notify("currLevel.levelNumber = " +                 currLevel.levelNumber);
        notify("currLevel.minXp = " +                         currLevel.minXp);
        notify("currLevel.maxXp = " +                         currLevel.maxXp);
        notify("temp:"+temp);
        MovieClip(root).LoaderBar.startup()
        GameServices.google.snapshots.addEventListener(SnapshotsEvents.GET_LIST, onSnapshotLoadList);
        GameServices.google.snapshots.getList(true);
        
        
}

function onLoginError(e:AuthEvents):void
{
        notify("onLoginError: "+ e.msg);
}
//=========================================Get list=====================================================================
var cat:int=1
function onSnapshotLoadList(e:SnapshotsEvents):void
{

        if(e.snapshotList.length==0)
        {
        cat=2;
                notify("cat:"+cat)
                toSaveNewSnapshot()
                notify("yes new Snapshot Created")
                notify("Number of available saved games: " + e.snapshotList.length);
            notify("list of available saved games: " + e.snapshotList);

        }
        else 
        {
                cat=3;
                notify("cat:"+cat)
                notify("Number of available saved games: " + e.snapshotList.length);
            notify("list of available saved games: " + e.snapshotList);
                paneel()
                notify("snapshotList")
                list=e.snapshotList
        notify("-------------------------------------------------");
        }
        
}        

//=========================================save new snapshot=====================================================================
        
        var content:String 
        var no:String="Hfg";
        var SGname:String 
        function toSaveNewSnapshot():void
        { 
       
                GameServices.google.snapshots.addEventListener(SnapshotsEvents.SAVE_STARTED, onSnapshotSaveStarted);
            GameServices.google.snapshots.addEventListener(SnapshotsEvents.SAVE_ENDED, onSnapshotSaveEnded);
                SGname= man+no;
                content = JSON.stringify(MovieClip(parent).sharedobj3);
                var description:String = "Saved Game of Halloween 2016";
                var progressValue:Number = 20;
                var playedTime:Number = 123456;
                notify("to Save New Snapshot...");
            notify("SGname..."+SGname);
                notify("var")
                notify("description");
                try
                {
                        var coverImgBmd:BitmapData = new BitmapData(200,200);
                }
                catch(e)
                {
                        notify(e);
                }
                notify("GameServices.google.snapshots");
                GameServices.google.snapshots.save(SGname, content, description, coverImgBmd, progressValue, playedTime, 4);
                GameServices.google.snapshots.addEventListener(SnapshotsEvents.GET_LIST, onSnapshotLoadList);
                GameServices.google.snapshots.getList(true);
                
                
        }
        
        
        function onSnapshotSaveStarted(e:SnapshotsEvents):void
        {
                notify("Save Started > " + e.snapshotName);        
            notify("123123123 > " +content);
                
        }
        function onSnapshotSaveEnded(e:SnapshotsEvents):void
        {
                
                notify("Save Ended > " + e.status);
            notify("456456456 > " +content);
                
        }
//=========================================load snapshot=====================================================================
        var list:Array ;
        function toLoadSnapshot():void
        {
                notify("loadddddddddddddddd")
                var myArray:Array = [list]
                notify(myArray[0]);
                if(myArray)
                {
                        GameServices.google.snapshots.load(myArray[0]);
                        GameServices.google.snapshots.addEventListener(SnapshotsEvents.LOAD_STARTED, onSnapshotLoadStarted);
                        GameServices.google.snapshots.addEventListener(SnapshotsEvents.LOAD_ENDED, onSnapshotLoadEnded);
                        
                }
                
        }
        
        function onSnapshotLoadStarted(e:SnapshotsEvents):void
        {

                notify("Load Started > " + e.snapshotName);
                GameServices.google.snapshots.load(e.snapshotName);
                GameServices.google.snapshots.removeEventListener(SnapshotsEvents.LOAD_STARTED, onSnapshotLoadStarted);
                
        }     
        function onSnapshotLoadEnded(e:SnapshotsEvents):void
        {
                // use the GamesStatusCodes class to see what each status code means
        
                notify("------------ Load Ended status: " + e.status);
                notify("e.snapshot.uniqueName = " + e.snapshot.uniqueName);
                notify("e.snapshot.description = " + e.snapshot.description);
                notify("e.snapshot.lastModifiedTimestamp = " + e.snapshot.lastModifiedTimestamp.toLocaleDateString());
                notify("e.snapshot.playedTime = " + e.snapshot.playedTime);
                notify("e.snapshot.progressValue = " + e.snapshot.progressValue);
                notify("e.snapshot.content = " + e.snapshot.content);
                content = e.snapshot.content
                CloudRetrieve()
                notify("went to sharedfun")
                GameServices.google.snapshots.removeEventListener(SnapshotsEvents.LOAD_ENDED, onSnapshotLoadEnded);
                

        }
//=========================================Retrive snapshot Data=====================================================================
    var CloudObject:Object;
        var sharedfromgoogle:String;
              function CloudRetrieve():void
                        {
                                CloudObject = new Object()
                                notify("jjghfjghfghkjnfgh:"+content)
                                CloudObject = JSON.parse(content.toString())
                                notify("bbbbbbbbbbbbbbb:"+ CloudObject)
                                for(var id:String in CloudObject) 
                                        {
                                                var value:Object = CloudObject[id];
                                                notify("SaveData-MC Process: "+id + " = " + value);
                                           // notify("nnnnnnnnnnnnnn:"+ content)
                                        }
                                MovieClip(parent).sharedobj3 = CloudObject
                        MovieClip(parent).retriveDatas1();
                                
                        }
//===========================================Buttons===================================================================
 panel.btn1.addEventListener(MouseEvent.CLICK,restore)
                        function restore(e:MouseEvent):void
                        {
                                panel.visible=false
                                toLoadSnapshot()
                        }
panel.btn2.addEventListener(MouseEvent.CLICK,normal)
                        function normal(e:MouseEvent):void
                        {
                                panel.visible=false
                                
                        }

function onSnapshotLoad():void
{
        toSaveNewSnapshot()
}

//==============================================================================================================
function paneel()
{
        notify("paneel:")
        if(MovieClip(root).backup==false && cat==3 )
        {
                panel.visible=true
        }
        else
        {
                panel.visible=false
        }
        
}        

function datalose():void
{
        if(MovieClip(root).backup==true && MovieClip(root).totalCoins==0 && MovieClip(root).totalCoins > 0)
        {
                toLoadSnapshot()
        }
        
}

**Comment by myflashlab** [comment]
It seems like you are using an older version of gameservices ANE. the new version is using GoogleSignIn and doing authentication inside the ANE is deprecated. This is forced by Google and we had to update our ANEs accordingly.

Now, you are using an older version of game services and probably newer version of Admob... their dependencies might be different and maybe that's why they behave strangely.

I would suggest you to first upgrade your project with the latest available ANEs and then see if it's anything wrong there.

Admob and GameServices ANEs don't have anything in common except their dependencies. So, there's a very high probability that updating to the latest version will solve the question automatically. So, I'm closing the issue, but in case you had questions after the upgrade, please do let us know to re-open the case. Thanks.
