### ISSUE TITLE
Banner and Interstitial are onFailed

### ISSUE THREAD

**Issue by jincang** [myflashlab/Admob-ANE#38]
Before opening a new issue, make sure you are using the latest available ANE. If the ANE is dependent on other libraries or dependencies, also make sure they are the latest versions.

## Environment ##
* Android API Version: 
* iOS Version:
* AIR SDK Version: 29
Admob Air Native Extension  *Jun 14, 2018 - V3.0.0*

## Problem Description ##

I purchased the  admob.ane today. And have a test use it. But can load the ad. banner and Interstitial all trigger onAdFailed Event. I use the FirebaseAnalytics.ane from myflashlab.

This is the log:
AdmobANE(AirCommand) initialize started...
AdmobANE(AirCommand) initialize finished
AdmobANE(AirCommand) setting layers started...
AdmobANE(AirCommand) setting layers finished
AdmobANE(AirCommand) initBanner started...
AdmobANE(AirCommand) initBanner finished, Now we are waiting for the banner real width/height
AdmobANE(AirCommand) convertJsonToRequest begin
AdmobANE(AirCommand) we do NOT have NetworkExtrasBundle
AdmobANE(AirCommand) convertJsonToRequest end
onBannerAdSizeReceived__e.height=100_____e.width=640
onBannerAdSizeReceived__e.height=100_____e.width=640
onAdFailed___e.adType=banner

AdmobANE(AirCommand) initInterstitial started...
AdmobANE(AirCommand) initInterstitial finished
AdmobANE(AirCommand) convertJsonToRequest begin
AdmobANE(AirCommand) we do NOT have NetworkExtrasBundle
AdmobANE(AirCommand) convertJsonToRequest end
onAdFailed___e.adType=interstitial

* Copy your manifest ```.xml``` file.
```xml

<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    <!--See the Adobe AIR documentation for more information about setting Google Android permissions-->
			    <!--Removing the permission android.permission.INTERNET will have the side effect
					of preventing you from debugging your application on your device-->
			    
			    <!--<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>-->
			    <!--<uses-permission android:name="android.permission.READ_PHONE_STATE"/>-->
			    <!--<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>-->
			    <!--The DISABLE_KEYGUARD and WAKE_LOCK permissions should be toggled together
					in order to access AIR's SystemIdleMode APIs-->
			    <!--<uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>-->
			    <!--<uses-permission android:name="android.permission.WAKE_LOCK"/>-->
			    <!--<uses-permission android:name="android.permission.CAMERA"/>-->
			    <!--<uses-permission android:name="android.permission.RECORD_AUDIO"/>-->
			    <!--The ACCESS_NETWORK_STATE and ACCESS_WIFI_STATE permissions should be toggled
					together in order to use AIR's NetworkInfo APIs-->
		
				<uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
			    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
			    <uses-permission android:name="android.permission.WAKE_LOCK"/>
			    <!-- 
					Required by firebase_iid.ane 
					Change "air.com.doitflash.firebaseCore" to your own app package name
				-->
			    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
				<permission android:name="air.com.shenmayouxi.AssembleSuperRobots.permission.C2D_MESSAGE" android:protectionLevel="signature" />
				<uses-permission android:name="air.com.shenmayouxi.AssembleSuperRobots.permission.C2D_MESSAGE" />
				
			    
			     <application android:name="android.support.multidex.MultiDexApplication">
			    	<meta-data
            			android:name="com.google.android.gms.version"
            			android:value="@integer/google_play_services_version" />
			  	    <activity
            			android:name="com.google.android.gms.ads.AdActivity"
            			android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            			android:theme="@android:style/Theme.Translucent"/>
            			
            		
            		<activity>
						<intent-filter>
							<action android:name="android.intent.action.MAIN" />
							<category android:name="android.intent.category.LAUNCHER" />
						</intent-filter>
						<intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.BROWSABLE" />
							<category android:name="android.intent.category.DEFAULT" />
							
							<!-- Change "air.com.doitflash.firebaseCore" to your own app package name -->
							<data android:scheme="air.com.shenmayouxi.AssembleSuperRobots" />
						</intent-filter>
					</activity>
					
					
					
					
					<!--
	                    Required by the firebase_common.ane
	                    Change "air.com.doitflash.firebaseCore" to your own app package name-->
	                
	                <provider
	                    android:name="com.google.firebase.provider.FirebaseInitProvider"
	                    android:authorities="air.com.shenmayouxi.AssembleSuperRobots.firebaseinitprovider"
	                    android:exported="false"
	                    android:initOrder="100"/>
	
	                <service
	                    android:name="com.myflashlab.firebase.core.MyFirebaseInstanceIdService"
	                    android:exported="true">
	                    <intent-filter>
	                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
	                    </intent-filter>
	                </service>
                
                
                <!-- Required by googlePlayServices_basement.ane -->
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
            
                <!--
                    Required by firebase_iid.ane
                    Change "air.com.doitflash.firebaseCore" to your own app package name
                -->
                <receiver
                    android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
                    android:exported="true"
                    android:permission="com.google.android.c2dm.permission.SEND">
                    <intent-filter>
                        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                        <category android:name="air.com.doitflash.firebaseCore"/>
                    </intent-filter>
                </receiver>
                <service
                    android:name="com.google.firebase.iid.FirebaseInstanceIdService"
                    android:exported="true">
                    <intent-filter android:priority="-500">
                        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
                    </intent-filter>
                </service>
            
                <!-- Required by googlePlayServices_base.ane -->
                <activity android:name="com.google.android.gms.common.api.GoogleApiActivity"
                    android:theme="@android:style/Theme.Translucent.NoTitleBar"
                    android:exported="false"/>
                
                
                
                
                <!-- Required by firebase_analyticsImpl.ane and firebase-analytics.ane -->
            	<receiver
					android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
					android:enabled="true" 
					android:exported="false">
				</receiver>
				<receiver 
					android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver" 
					android:permission="android.permission.INSTALL_PACKAGES" 
					android:enabled="true">
					<intent-filter>
						<action android:name="com.android.vending.INSTALL_REFERRER"/>
					</intent-filter>
				</receiver>
				<service
					android:name="com.google.android.gms.measurement.AppMeasurementService"
					android:enabled="true"
					android:exported="false"/>
					
				
				<service
                    android:name="com.google.android.gms.measurement.AppMeasurementJobService"
                    android:permission="android.permission.BIND_JOB_SERVICE"
                    android:enabled="true"
                    android:exported="false"/>
                    
				</application>
			</manifest>
			
		]]></manifestAdditions>
    </android>
    <iPhone>
        <InfoAdditions><![CDATA[
            <key>UIDeviceFamily</key>
            <array>
                <string>1</string>
                <string>2</string>
            </array>
            <key>MinimumOSVersion</key>
			<string>8.0</string>
            <key>NSAppTransportSecurity</key>
            <dict>
             <key>NSAllowsArbitraryLoads</key>
             <true/>
            </dict>
        ]]></InfoAdditions>
        
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>
<extensions>
        
    
    
   <extensionID>com.myflashlab.air.extensions.dependency.firebase.common</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.iid</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.appinvite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
        
    <extensionID>com.myflashlab.air.extensions.firebase.core</extensionID>
   
    
    
    
    
        
    <extensionID>com.myflashlab.air.extensions.firebase.analytics</extensionID>
    
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics.impl</extensionID>
        
    <extensionID>com.myflashlab.air.extensions.dependency.firebase.analytics</extensionID>
    
    
    
    
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    </extensions>
```
```actionscript
* Copy your Actionscript code.

private function addedToStage(e:Event):void{
			
			AdMob.init(stage, "ca-app-pub-9245796577237541~1428607117");
			
			// Add general listeners for the Ads

			AdMob.api.addEventListener(AdMobEvents.AD_FAILED, 	onAdFailed);
			AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
			AdMob.api.banner.init("ca-app-pub-9245796577237541/2905340315", ApiBannerAds.BANNER);
			
			AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, 	onBannerAdSizeReceived);
			
			var adRequest:AdRequest = new AdRequest();
			adRequest.gender = AdRequest.GENDER_UNKNOWN;
			//adRequest.extras = {npa:1};
			
			AdMob.api.banner.loadAd(adRequest);

		}
		
		private function onBannerAdSizeReceived(e:AdMobEvents):void
		{
			trace("onBannerAdSizeReceived__e.height="+e.height+"_____e.width="+e.width);
			trace("onBannerAdSizeReceived__e.height="+AdMob.api.banner.height+"_____e.width="+AdMob.api.banner.width);
		}
		private function onAdLoaded(e:AdMobEvents):void
		{
			trace("onAdLoaded");
			if (e.adType == AdMob.AD_TYPE_BANNER)
			{
				// place the Ad at the center of your game, or anywhere else you wish!
				AdMob.api.banner.x = stage.stageWidth / 2 - AdMob.api.banner.width / 2;
				AdMob.api.banner.y = stage.stageHeight / 2 - AdMob.api.banner.height / 2;
			}
			if (e.adType == AdMob.AD_TYPE_INTERSTITIAL)
			{
				if(AdMob.api.interstitial.isLoaded)
				{
					AdMob.api.interstitial.show();
				}
			}
		} 
		private function onAdFailed(e:AdMobEvents):void
		{
			trace("onAdFailed___e.adType="+e.adType);
		}


protected function loadInterstitial(event:Event):void
		{
			AdMob.api.interstitial.init("ca-app-pub-9245796577237541/4382073514");
			var adRequest:AdRequest = new AdRequest();
			adRequest.gender = AdRequest.GENDER_UNKNOWN;

			//adRequest.extras = {npa:1};
			AdMob.api.interstitial.loadAd(adRequest);
		}

```

This is the log:
AdmobANE(AirCommand) initialize started...
AdmobANE(AirCommand) initialize finished
AdmobANE(AirCommand) setting layers started...
AdmobANE(AirCommand) setting layers finished
AdmobANE(AirCommand) initBanner started...
AdmobANE(AirCommand) initBanner finished, Now we are waiting for the banner real width/height
AdmobANE(AirCommand) convertJsonToRequest begin
AdmobANE(AirCommand) we do NOT have NetworkExtrasBundle
AdmobANE(AirCommand) convertJsonToRequest end
onBannerAdSizeReceived__e.height=100_____e.width=640
onBannerAdSizeReceived__e.height=100_____e.width=640
onAdFailed___e.adType=banner

AdmobANE(AirCommand) initInterstitial started...
AdmobANE(AirCommand) initInterstitial finished
AdmobANE(AirCommand) convertJsonToRequest begin
AdmobANE(AirCommand) we do NOT have NetworkExtrasBundle
AdmobANE(AirCommand) convertJsonToRequest end
onAdFailed___e.adType=interstitial

## Steps to Reproduce ##
Tell us how this issue can be reproduced.

## Known Workarounds ##
Just in case others run into this – do you happen to know of a workaround? Otherwise, just remove this section altogether.

**Comment by myflashlab** [comment]
When an adFailed happens, please also check what is the error code. check the sample codes for example: https://github.com/myflashlab/Admob-ANE/blob/master/AIR/src/Demo.as#L367-L372

**Comment by jincang** [comment]
OK
This is the error info:
onAdFailed adType > banner
onAdFailed errorCode > 1
onAdFailed msg > null

onAdFailed adType > interstitial
onAdFailed errorCode > 1
onAdFailed msg > null

**Comment by jincang** [comment]
I see  errorCode > 1 means:
public static final int ERROR_CODE_INVALID_REQUEST
The ad request was invalid; for instance, the ad unit ID was incorrect.
Constant Value: 1

But my ad unit ID is correct.

AdMob.init(stage, "ca-app-pub-9245796577237541~1428607117");
			
			// Add general listeners for the Ads

			AdMob.api.addEventListener(AdMobEvents.AD_FAILED, 	onAdFailed);
			AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
			AdMob.api.banner.init("ca-app-pub-9245796577237541/2905340315", ApiBannerAds.BANNER);
			
			AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, 	onBannerAdSizeReceived);
			
			var adRequest:AdRequest = new AdRequest();
			adRequest.gender = AdRequest.GENDER_UNKNOWN;
			//adRequest.extras = {npa:1};
			
			AdMob.api.banner.loadAd(adRequest);

**Comment by jincang** [comment]
Hello myflashlab ！
Can you focus this issue and help me solve this problem today? I am very anxious.
Thank you very much!

**Comment by myflashlab** [comment]
Well, the returned error message is coming from native SDK and when it says the adunit is incorrect, it means that it is incorrect. We at the ANE side, have NO control over these things. Our job is to make the native code available to AIR. An Error like this which comes from native side is not something that we have control on. You may find better results on asking on stackoverflow.

However, here are some points which may be helpful.
1. If you are on Android, your application code is different from when you are on iOS.
2. The same thing is true about adunits. make sure you are using the correct ones.
3. When you create new adunits, it may take a few hours for them to properly propagate across Google servers.
4. You may also use test adunits for test reasons: https://developers.google.com/admob/android/test-ads#sample_ad_units

And finally we always suggest developers to run ANEs first in a demo empty app with the same package id of your main app. This way, you won't be distracted by other ANEs setups so you may find configuration mistakes faster and easier.

**Comment by jincang** [comment]
Thank you!

1. I create a empty app just use admob from myflashbab. 
2.My unitId is for android.
3.My unitId is  correct.

But the error is occur also.

This is the code:
AdMob.init(stage, "ca-app-pub-9245796577237541~1428607117");
			//AdMob.init(stage, "ca-app-pub-3940256099942544~3347511713");//test
			
			// Add general listeners for the Ads
//			AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, 				onAdClosed);
			AdMob.api.addEventListener(AdMobEvents.AD_FAILED, 				onAdFailed);
//			AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, 			onAdLeftApp);
			AdMob.api.addEventListener(AdMobEvents.AD_LOADED, 				onAdLoaded);
//			AdMob.api.addEventListener(AdMobEvents.AD_OPENED, 				onAdOpened);
			
			AdMob.api.banner.init("ca-app-pub-9245796577237541/2905340315", ApiBannerAds.BANNER);
			//AdMob.api.banner.init("ca-app-pub-3940256099942544/6300978111", ApiBannerAds.BANNER);//test
			
			AdMob.api.interstitial.init("ca-app-pub-9245796577237541/4382073514");
			//AdMob.api.interstitial.init("ca-app-pub-3940256099942544/1033173712");//test
			
			AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, 	onBannerAdSizeReceived);



protected function loadInterstitial(event:Event):void
		{

			trace("load interstitial ad");
			var adRequest:AdRequest = new AdRequest();
			AdMob.api.interstitial.loadAd(adRequest);
		}

protected function loadBanner(event:Event):void
		{

			var adRequest:AdRequest = new AdRequest();
			AdMob.api.banner.loadAd(adRequest);
		}

private function onBannerAdSizeReceived(e:AdMobEvents):void
		{
			trace("onBannerAdSizeReceived__e.height="+e.height+"_____e.width="+e.width);
			trace("onBannerAdSizeReceived__e.height="+AdMob.api.banner.height+"_____e.width="+AdMob.api.banner.width);
		}
		private function onAdLoaded(e:AdMobEvents):void
		{
			trace("onAdLoaded");
			if (e.adType == AdMob.AD_TYPE_BANNER)
			{
				// place the Ad at the center of your game, or anywhere else you wish!
				AdMob.api.banner.x = stage.stageWidth / 2 - AdMob.api.banner.width / 2;
				AdMob.api.banner.y = stage.stageHeight / 2 - AdMob.api.banner.height / 2;
			}
			if (e.adType == AdMob.AD_TYPE_INTERSTITIAL)
			{
				if(AdMob.api.interstitial.isLoaded)
				{
					AdMob.api.interstitial.show();
				}
			}
		} 
		private function onAdFailed(e:AdMobEvents):void
		{
			trace("onAdFailed adType > " + e.adType); // AdMob.AD_TYPE_*
			trace("onAdFailed errorCode > " + e.errorCode); // AdMob.ERROR_CODE_*
			trace("onAdFailed msg > " + e.msg);
			
		}
		




This is Main-app.xml:

<android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
			    
		
				<uses-permission android:name="android.permission.INTERNET"/>
			    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
			    
			   
				<uses-sdk android:targetSdkVersion="23"/>
			    
			     <application>
		
					<activity>
						<intent-filter>
							<action android:name="android.intent.action.MAIN" />
							<category android:name="android.intent.category.LAUNCHER" />
						</intent-filter>
						<intent-filter>
							<action android:name="android.intent.action.VIEW" />
							<category android:name="android.intent.category.BROWSABLE" />
							<category android:name="android.intent.category.DEFAULT" />
						</intent-filter>
					</activity>
					
					
			        <activity
			            android:name="com.google.android.gms.ads.AdActivity"
			            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
			            android:theme="@android:style/Theme.Translucent" />
						
					<meta-data
			            android:name="com.google.android.gms.version"
			            android:value="@integer/google_play_services_version" />
					
				</application>
			</manifest>
			
		]]></manifestAdditions>
    </android>
    <iPhone>
        <InfoAdditions><![CDATA[
            <key>UIDeviceFamily</key>
            <array>
                <string>1</string>
                <string>2</string>
            </array>
            <key>MinimumOSVersion</key>
			<string>8.0</string>
            <key>NSAppTransportSecurity</key>
            <dict>
             <key>NSAllowsArbitraryLoads</key>
             <true/>
            </dict>
        ]]></InfoAdditions>
        
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>
<extensions>
        
    
    
   
    
    
    
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
        
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    </extensions>
</application>

**Comment by jincang** [comment]
My unitId is No problem , because I use another admob ane can load and show Ad.
So I thought my code or my xml is wrong. But I do not know there...

**Comment by jincang** [comment]
My unitId is No problem , because I use another admob ane can load and show Ad.
When I use google provide unitId , the error is occur too.
So I thought my code or my xml is wrong. But I do not know where is the wrong...

**Comment by jincang** [comment]
My unitId is No problem , because I use another admob ane can load and show Ad.
When I use google provide unitId , the error is occur too.
So I thought my code or my xml is wrong. But I do not know where is the wrong...

Please help me, thanks.

**Comment by jincang** [comment]
This is the message on FlashBuilder Console, a question : "we do NOT have NetworkExtrasBundle" is normal?

AdmobANE(AirCommand) initialize started...
AdmobANE(AirCommand) initBanner started...
AdmobANE(AirCommand) initInterstitial started...
AdmobANE(AirCommand) initInterstitial finished
[SWF] MobileSuperRobots_eeempty.swf - 2,895 bytes after decompression
load interstitial
AdmobANE(AirCommand) convertJsonToRequest begin
AdmobANE(AirCommand) we do NOT have NetworkExtrasBundle
AdmobANE(AirCommand) convertJsonToRequest end
load banner
AdmobANE(AirCommand) convertJsonToRequest begin
AdmobANE(AirCommand) we do NOT have NetworkExtrasBundle
AdmobANE(AirCommand) convertJsonToRequest end

**Comment by jincang** [comment]
Here is my Flashbuilder project.
It's a empty project just include admob ane. Please see the issue.
[MobileSuperRobots_eeempty.zip](https://github.com/myflashlab/Admob-ANE/files/2140752/MobileSuperRobots_eeempty.zip)

**Comment by myflashlab** [comment]
Well, I just ran your .apk file ```MobileSuperRobots_eeempty.apk``` and banner and Interstitial ads are both loading and showing when I touched over the stage! All normal!

**Comment by jincang** [comment]
Yes？
My phone os is Android 5.1 
This ane not support Android 5.1?
It related to the Android version?

**Comment by myflashlab** [comment]
it does, Android 5 is fine. Have you checked on your other devices?

**Comment by jincang** [comment]
Yes, I test on Android 5.1,Android 6.0, Android 7.0, Android 8.0
Android 7.0, Android 8.0 Can load and show AD, Android 5.1,Android 6.0 load failed.
Please make sure your Android 5 device is fine?

**Comment by jincang** [comment]
On os Android 8.0 the admob ane works, indicates my unitId is correct.
Why on Flashbuilder console output:
"onAdFailed errorCode > 1
onAdFailed msg > null"

Google's explain is:
The ad request was invalid; for instance, the ad unit ID was incorrect.
Constant Value: 1

This is my request code:
protected function loadBanner(event:Event):void
		{
			trace("load banner");
			var adRequest:AdRequest = new AdRequest();
			AdMob.api.banner.loadAd(adRequest);
		}
		
		protected function loadInterstitial(event:Event):void
		{
			trace("load interstitial");
			var adRequest:AdRequest = new AdRequest();
			AdMob.api.interstitial.loadAd(adRequest);
		}


Where is the mistake？

**Comment by myflashlab** [comment]
We will be investigating this more and let you know the results.

**Comment by jincang** [comment]
Thank you ,this is my Flashbuilder project:
[MobileSuperRobots_eeempty.zip](https://github.com/myflashlab/Admob-ANE/files/2145011/MobileSuperRobots_eeempty.zip)

**Comment by jincang** [comment]
This is my Flashbuilder project:
[MobileSuperRobots_eeempty.zip](https://github.com/myflashlab/Admob-ANE/files/2145013/MobileSuperRobots_eeempty.zip)

**Comment by myflashlab** [comment]
Ok, we tested this specifically on Android 5.1 and all ads are showing just fine!

**Comment by jincang** [comment]
[MobileSuperRobots_eeempty.apk.zip](https://github.com/myflashlab/Admob-ANE/files/2175370/MobileSuperRobots_eeempty.apk.zip)

Please test this .apk, and make sure it can show ads on Android 5.1 .

Thanks!

**Comment by flashomer** [comment]
I have the same problems. Did you find a solution?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
