### ISSUE TITLE
iOS problem, ads not showing

### ISSUE THREAD

**Issue by andruvoicu** [myflashlab/Admob-ANE#41]
Hi, I have purchased your ANE file from your website. For my android app everything works fine (interstitial and reward ads) but for my ios app ads are now showing. No interstitials and no reward ads are showing. I doubled checked my ids for my ads and for my admob account and everything is good. When ads should appear, only an AD_FAILED event occurs. Does my ios app has to be published for my ads to work?
Please help!
Many thanks!

**Comment by myflashlab** [comment]
This usually happen when new adUnit IDs are created. try to test with demo IDs and you should see that they work fine. It's really something that happens from Google servers and not related to the ANE.

**Comment by andruvoicu** [comment]
Thank's mate!
