### ISSUE TITLE
Save Process

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/Admob-ANE#42]
sir, 
   I am using GameServices Ane for Cloud Save process it is working perfectly. There is  no issue in saving the data in cloud but i have small doubt  about e.conflict.serverSnapshot.lastModifiedTimestamp.toLocaleString()   can i use lastModifyTimestamp before Save Started because if i am playing the game in one mobile and after sometime i am playing in another mobile without clicking load button if i entered into the game it will save automically so what i played in previous mobile data will be lost so if i get lastModifyTimestamp they i can check the condition for snapshot last update.so that i can show pop up message to the user.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
