### ISSUE TITLE
Admob banners rarely show

### ISSUE THREAD

**Issue by LeapingSwan** [myflashlab/Admob-ANE#43]
Hi

This issue was originally posted on the wrong repository so now moved here and updated for latest info.

AIR SDK 30.0
iOS Minimum 8.0 or Higher

I am using the demo version of the Admob plugin until I am satisfied it works.

I am getting banner ads on rare occasions but most of the time they don't show on screen. Traces show that they are being loaded (I am triggering the onBannerLoaded event ok). This is true for my own ad IDs and also for the Admob test ID's.

I have checked my admob account but can see no problems there and in any event this also does not work with the test ad unit IDs. Happy to provide my own ad unit ID's privately.

My code is:

		private function setUpAds() 
		{
			OverrideAir.enableDebugger(myDebuggerDelegate);

			trace("OverrideAir.os " + OverrideAir.os);
			// initialize AdMob and pass in the Adobe AIR Stage and your AdmMob ApplicationCode
			if(OverrideAir.os == AdMob.ANDROID) 
			{
				trace("Initiate Android");
				AdMob.init(stage, "ca-app-pub-xxxxxxxxxxxxxxxxxxx")
				

			} else if(OverrideAir.os == AdMob.IOS) 
			{
			
				trace("Initiate iOS");
				
				AdMob.init(stage, "ca-app-pub-xxxxxxxxxxxxxxxxxx");
				
			}else{
				trace("Not iOS or Android")
			}
			
			AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, onAdClosed);
			AdMob.api.addEventListener(AdMobEvents.AD_FAILED, onAdFailed);
			AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, onAdLeftApp);
			AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
			AdMob.api.addEventListener(AdMobEvents.AD_OPENED, onAdOpened);

			// listen to the banner Ad to get its final width/height in pixels so you can place it anywhere you like in your Air app
			AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);
			
			
			
			trace("setUpAds completed");

		}

		
		private function showBanner(cEvent:CustomEvent)
		{
			trace("SB Constants.currentBanner " + Constants.currentBanner);
			AdMob.api.banner.init(Constants.currentBanner, ApiBannerAds.BANNER);
			
			adRequest = new AdRequest();
			
			adRequest.testDevices = [
				"zzzzzzzzzzzzzzzzzzzzzzzzzzzz"
				];
			
			
			AdMob.api.banner.loadAd(adRequest);
			
			

		}

		// If you wish to change the position of the loaded banner, which is (0, 0) by default, you should listen for AdMobEvents.AD_LOADED
		private function onAdLoaded(e:AdMobEvents):void
		{

			trace("onAdLoaded " + e.adType);
			if (e.adType == AdMob.AD_TYPE_BANNER)
			{
				trace("placing ad");
				AdMob.api.banner.x = Constants.MidX - (AdMob.api.banner.width / 2);
				AdMob.api.banner.y = Constants.MidY - (AdMob.api.banner.height / 2);
				trace("AdMob.api.banner.x " + AdMob.api.banner.x);
				trace("AdMob.api.banner.y " + AdMob.api.banner.y);
				
			}else{
				trace("no add position");
			}
	
		}

I have enabled the debugger and debugger traces can be seen preceded by "DDDDDDDDDDDD" and closed by "******************".

Used the app on a real device, getting traces via Adobe Scout.  

Tried to get the banner ad from the live adUnits first and then the test adUnits but same result (I have a button on the app which allows me to switch the adUnits).

Tried to use .BANNER and .SMART_BANNER_PORTRAIT.

Ads are not initiated until after the device has had time to re-size correctly and the traces show size and position as expected, which should put the ad centre screen.  On rare occasions when the ad appears this does work correctly.  Also this position works fine for interstitial and reward videos.

All this produces the following traces:

OverrideAir.os ios
Initiate iOS
setUpAds completed
startBanner
SB Constants.currentBanner ca-app-pub-zzzzzzzzzzzzzzzzzzzzzzzzzz
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) initBanner started...
********************************
e.errorCode -1
e.height 70
e.width 1827
e.toString() [Event type="onBannerSizeMeasured" bubbles=false cancelable=false eventPhase=2]
onBannerAdSizeReceived
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) initBanner finished
********************************
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) convertJsonToRequest begin
********************************
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) convertJsonToRequest end
********************************
onAdLoaded banner
placing ad
x = -351
y = 1183
AdMob.api.banner.x -351
AdMob.api.banner.y 1183
Setting Ads to Test
startBanner
SB Constants.currentBanner ca-app-pub-3940256099942544/2934735716
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) initBanner started...
********************************
e.errorCode -1
e.height 70
e.width 1827
e.toString() [Event type="onBannerSizeMeasured" bubbles=false cancelable=false eventPhase=2]
onBannerAdSizeReceived
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) initBanner finished
********************************
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) convertJsonToRequest begin
********************************
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
AdmobANE(BaseClassAdmob) convertJsonToRequest end
********************************
onAdLoaded banner
placing ad
x = -351
y = 1183
AdMob.api.banner.x -351
AdMob.api.banner.y 1183

So to me this seems like a display issue of some sort.  What confuses me is that sometimes, albeit rarely, it does show up and in the right place

Thanks for your help.

Stephen

**Comment by mysadjob** [comment]
Hi leapingswan,
can you please send me the admob .fla and .as file
coz am facing some issue.
my id ismailtanithu@gmail.com

Thanks

**Comment by mysadjob** [comment]
Hi leapingswan,
can you please send me the admob .fla and .as file
coz am facing some issue.
my id is     mailtanithu@gmail.com

Thanks

**Comment by LeapingSwan** [comment]
Hi mysadjob,

Sorry the code is part of a much bigger project which I can't share.  However all I did was to put in a very short delay before setting up the ads after the file is loaded. I started with a delay or 30 seconds and then reduced it until it worked consistently, which for me was just 0.2 seconds.  Of course the app for me is doing other things so there may be an inherent delay while it's setting up other stuff so the delay you need might be longer or shorter so I suggest a bit of trial and error.  By going larger at the start you will establish at least if this is the issue.  If it does not solve the problem then you may need to look elsewhere.

I hope that works for you.

**Comment by mysadjob** [comment]
Hi,
I have followed all the steps given in your page.
But i can't find where i did mistake...please help me and correct my given below.

Error Facing while exporting..but i can able to publish.
TypeError: Error #1009: Cannot access a property or method of a null object reference.
at jum1_fla::MainTimeline/frame1()[jak1_fla.MainTimeline::frame1:14]
at runtime::ContentPlayer/loadInitialContent()
at runtime::ContentPlayer/playRawContent()
at runtime::ContentPlayer/playContent()
at runtime::AppRunner/run()
at ADLAppEntry/run()
at global/runtime::ADLEntry()

I have added ANE file lists are:
admob.ane
overrideAir.ane
androidsupport_v27.0.2_lite.ane
googleplayservices_basement.ane
googleplayservices_adslite.ane

Copy your manifest .xml file.
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>


<application>
	
	<activity>
		<intent-filter>
			<action android:name="android.intent.action.MAIN" />
			<category android:name="android.intent.category.LAUNCHER" />
		</intent-filter>
		<intent-filter>
			<action android:name="android.intent.action.VIEW" />
			<category android:name="android.intent.category.BROWSABLE" />
			<category android:name="android.intent.category.DEFAULT" />
		</intent-filter>
	</activity>
	
	
    <activity
        android:name="com.google.android.gms.ads.AdActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
        android:theme="@android:style/Theme.Translucent" />
		
	<meta-data
        android:name="com.google.android.gms.version"
        android:value="@integer/google_play_services_version" />
	
</application>
]]>
en

com.myflashlab.air.extensions.admob com.myflashlab.air.extensions.dependency.overrideAir com.myflashlab.air.extensions.dependency.androidSupport com.myflashlab.air.extensions.dependency.googlePlayServices.basement com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite
Copy your Actionscript code.
import flash.events.MouseEvent;
import com.myflashlab.air.extensions.admob.*;
import com.myflashlab.air.extensions.dependency.OverrideAir;

if(OverrideAir.isSupported)
{
AdMob.init(stage, "ca-app-pub-9002001127208746~3709582175");
trace("Android ")
}

AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, onAdClosed);
AdMob.api.addEventListener(AdMobEvents.AD_FAILED, onAdFailed);
AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, onAdLeftApp);
AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
AdMob.api.addEventListener(AdMobEvents.AD_OPENED, onAdOpened);

//AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);

var adRequest:AdRequest = new AdRequest();
adRequest.testDevices = ["an array of device IDs so you can receive test Ads when developing!"];
adRequest.extras = {npa:1}; // npa stands for "Non-Personalized Ads"

btn0.addEventListener(MouseEvent.CLICK,banad);
function banad(e:MouseEvent){
AdMob.api.banner.init("ca-app-pub-930840122057342/5256142323", ApiBannerAds.BANNER);
AdMob.api.banner.loadAd(adRequest);

}
btn1.addEventListener(MouseEvent.CLICK,banint);
function banint(e:MouseEvent){
AdMob.api.interstitial.init("ca-app-pub-9476398060240162/1457820116");
AdMob.api.interstitial.loadAd(adRequest);

}
btn2.addEventListener(MouseEvent.CLICK,banrew);
function banrew(e:MouseEvent){
AdMob.api.rewardedVideo.loadAd(adRequest, "ca-app-pub-9202401623205742/3427670519");

}

function onAdLoaded(e:AdMobEvents):void
{
trace("onAdLoaded > " + e.adType); // AdMob.AD_TYPE_*

if (e.adType == AdMob.AD_TYPE_BANNER)
{
	
	AdMob.api.banner.x = stage.stageWidth / 2 - AdMob.api.banner.width / 2;
	AdMob.api.banner.y = stage.stageHeight / 2 - AdMob.api.banner.height / 2;
}
else if (e.adType == AdMob.AD_TYPE_INTERSTITIAL)
{
	if(AdMob.api.interstitial.isLoaded)
	{
		AdMob.api.interstitial.show();
	}
}
else if (e.adType == AdMob.AD_TYPE_REWARDED_VIDEO)
{
	
}
}

function onAdClosed(e:AdMobEvents):void
{
trace("onAdClosed > " + e.adType); // AdMob.AD_TYPE_*
}

function onAdFailed(e:AdMobEvents):void
{
trace("onAdFailed > " + e.adType); // AdMob.AD_TYPE_*
trace("onAdFailed > " + e.errorCode); // AdMob.ERROR_CODE_*
}

function onAdLeftApp(e:AdMobEvents):void
{
trace("onAdLeftApp > " + e.adType); // AdMob.AD_TYPE_*
}

function onAdOpened(e:AdMobEvents):void
{
trace("onAdOpened > " + e.adType); // AdMob.AD_TYPE_*
}

Tell me the steps which i want to correct.
while opening apk..it showing you are using demo version of flashlab.

Hope i expect your positive reply.

**Comment by mysadjob** [comment]
could you please correct my code...

**Comment by LeapingSwan** [comment]
Hi mysadjob,

You need to first find what is tripping up your code.  The error you are seeing shows that you are trying to do something to a variable that has not yet been substantiated.  I suggest you put in a series of traces between each line to see which one you get to before the code fails.  That will help you close in on the problem.

I do have a suspicion though.  I see you are not getting the trace "Android".  I suspect therefore you are finding OverrideAir.isSupported is false so you are not initiating Admob.  When you then go on to call api's on Admob, Admob is coming up as null.  To check this put in the following traces:

trace("OverrideAir.isSupported " + OverrideAir.isSupported) before testing for it to find out if it's true or false.
Then after that piece of code include:
trace("Admob " + Admob) and see if thats is null or not.

If, as I suspect Override.Air is not supported you need to see why that is the case.  Two things on this:

a) Are you testing on a real device?  I believe that is a requirement.
b) You might want to also import firebase:
import com.myflashlab.air.extensions.firebase.core.*;

I hope that helps you isolate the problem and perhaps fix it.

Good luck.

**Comment by mysadjob** [comment]
i put trace, it showed as Desktop
but still same error.
i have downloaded common firebase ane files, there are so many which i want to use.

And i have used your above code also...it also having error as,

Type was not found or was a compile-time constant customevent.

Thanks

**Comment by myflashlab** [comment]
Thanks for the valid comments @LeapingSwan 

> i put trace, it showed as Desktop

It seems like you are running on the simulator. You shouldn't. The whole reason of using ```if(OverrideAir.isSupported)``` is to see if the running platform is supported or not. and simulators are always not supported.

So, as @LeapingSwan suggested, the ```if(OverrideAir.isSupported)``` returns false considering that your are not running on a real device, and then a few lines lower, you are accessing admob but ```AdMob.init``` has been never called.

**Comment by myflashlab** [comment]
Oh, and by the way, you don't need to use any of the Firebase ANEs. Although The Admob ANE and Firebase ANEs are working with each other internally, but they are both independent. So, if you are using Admob in your project only and you are not going to use Firebase in your project, then there's no reason to import anything related to Firebase.

**Comment by mysadjob** [comment]
sir, i want to run ad in my apk,,,
please help or send source file
tell me how much it cost..if possible i pay...

**Comment by myflashlab** [comment]
I believe I already told you what the problem was. please check my [message again](https://github.com/myflashlab/Admob-ANE/issues/43#issuecomment-412163497). Also, we have a sample project with full source code [here](https://github.com/myflashlab/Admob-ANE/tree/master/AIR).

In case you still can't run the project, you may [contact my colleagues](http://www.myflashlabs.com/contact/) and ask for a live Skype/Teamviewer session. Please ask for rates from them directly.

**Comment by mysadjob** [comment]
Hi,
i have used used your sample demo code and created apk.
But ad is not showing...it shows error as onAdFailed errorcode>0 and onAdFailed msg>null

Please help
![screenshot_2018-08-11-13-08-58-976_air ad 1](https://user-images.githubusercontent.com/42202632/43989482-3278f196-9d68-11e8-9efe-596bdf47132b.png)

**Comment by mysadjob** [comment]
how to add test devices id...whether it is necessary....

**Comment by mysadjob** [comment]
Sir, waiting for your reply

**Comment by LeapingSwan** [comment]
Hi mysadjob,

I'm not sure if it's me or myflashlab you are looking to get direct support from, paid or otherwise.  To be clear I am not looking to get involved in fixing other developers code and getting knee deep in your project - I've got enough of my own to fix.  Happy to give you a few suggestions here but you need to sort this yourself from comments from other contributors.  Myflash lab are the experts and helped me get through the learning curve.  It's also the weekend and as a rule I don't work weekends, especially not on someone else project.

That said, looking at some of the specific problems you are now having with the sample project:

1.  Error code 0 from admob suggests you are using Myflashlabs correctly but your Admob account is not working right.  If you Google Admob Error code 0 you'll get various answers related to account issues all of which might be your problem.
2.  Yes you do need to set up test devices if you are using your own Ad IDs but its not hard and juts a few lines of code.  But probably best first to use Admob's own test IDs which for Android you can get here:

https://developers.google.com/admob/android/test-ads

For iOS they are here:

https://developers.google.com/admob/ios/test-ads

**Comment by myflashlab** [comment]
@LeapingSwan again thanks for your time on your comments. we confirm that what you suggested above is all valid. @mysadjob please refer to the comment above. Moreover, check the sample project we have [here](https://github.com/myflashlab/Admob-ANE/blob/master/AIR/src/Demo.as#L215-L223) to see how test deviceIDs are entered to the ANE.

@mysadjob I am closing the issue now as your questions are not related to the main topic. However, feel free to open a new issue if you have more questions. And by the way, if you are a club member, you can drop us an email and link to your issue so we can assist you faster.

**Comment by mysadjob** [comment]
hi sir,
i need final help.

please send the file with having .fla and .as file. need only banner and interstitial script...
you please send with demo version .ane files....i will replace my .ane files...

this will be my last comment.

Thank you...
