### ISSUE TITLE
Banner,Interstitial and Reward Ad not showing

### ISSUE THREAD

**Issue by mysadjob** [myflashlab/Admob-ANE#44]
## Environment ##
* Android API Version:
* iOS Version:
* AIR SDK Version:29

## Problem Description ##
Hi,
I have followed all the steps given in your page.
But i can't find where i did mistake...please help me and correct my given below.

Error Facing while exporting..but i can able to publish.
```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at jum1_fla::MainTimeline/frame1()[jak1_fla.MainTimeline::frame1:14]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()
 ```
I have added ANE file lists are:
```
admob.ane
overrideAir.ane
androidsupport_v27.0.2_lite.ane
googleplayservices_basement.ane
googleplayservices_adslite.ane
```

```xml
<android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
	
	
	<application>
		
		<activity>
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.BROWSABLE" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		
		<!-- Include the AdActivity and InAppPurchaseActivity configChanges and themes. -->
        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />
			
		<meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
		
	</application>
</manifest>]]></manifestAdditions>
  </android>

  <supportedLanguages>en</supportedLanguages>
  
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
  </extensions>
</application>
```

```actionscript
import flash.events.MouseEvent;
import com.myflashlab.air.extensions.admob.*;
import com.myflashlab.air.extensions.dependency.OverrideAir;


if(OverrideAir.isSupported)
{
	AdMob.init(stage, "ca-app-pub-9002001127208746~3709582175");
	trace("Android ")
}


AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, 	onAdClosed);
AdMob.api.addEventListener(AdMobEvents.AD_FAILED, 	onAdFailed);
AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, 	onAdLeftApp);
AdMob.api.addEventListener(AdMobEvents.AD_LOADED, 	onAdLoaded);
AdMob.api.addEventListener(AdMobEvents.AD_OPENED, 	onAdOpened);

//AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, 	onBannerAdSizeReceived);

var adRequest:AdRequest = new AdRequest();
adRequest.testDevices = ["an array of device IDs so you can receive test Ads when developing!"];
adRequest.extras = {npa:1}; // npa stands for "Non-Personalized Ads"



btn0.addEventListener(MouseEvent.CLICK,banad);
function banad(e:MouseEvent){
	AdMob.api.banner.init("ca-app-pub-930840122057342/5256142323", ApiBannerAds.BANNER);
	AdMob.api.banner.loadAd(adRequest);

}
btn1.addEventListener(MouseEvent.CLICK,banint);
function banint(e:MouseEvent){
	AdMob.api.interstitial.init("ca-app-pub-9476398060240162/1457820116");
    AdMob.api.interstitial.loadAd(adRequest);

}
btn2.addEventListener(MouseEvent.CLICK,banrew);
function banrew(e:MouseEvent){
	AdMob.api.rewardedVideo.loadAd(adRequest, "ca-app-pub-9202401623205742/3427670519");

}

function onAdLoaded(e:AdMobEvents):void
{
	trace("onAdLoaded > " + e.adType); // AdMob.AD_TYPE_*
	
	if (e.adType == AdMob.AD_TYPE_BANNER)
	{
		
		AdMob.api.banner.x = stage.stageWidth / 2 - AdMob.api.banner.width / 2;
		AdMob.api.banner.y = stage.stageHeight / 2 - AdMob.api.banner.height / 2;
	}
	else if (e.adType == AdMob.AD_TYPE_INTERSTITIAL)
	{
		if(AdMob.api.interstitial.isLoaded)
		{
			AdMob.api.interstitial.show();
		}
	}
	else if (e.adType == AdMob.AD_TYPE_REWARDED_VIDEO)
	{
		
	}
}

 function onAdClosed(e:AdMobEvents):void
{
	trace("onAdClosed > " + e.adType); // AdMob.AD_TYPE_*
}

 function onAdFailed(e:AdMobEvents):void
{
	trace("onAdFailed > " + e.adType); // AdMob.AD_TYPE_*
	trace("onAdFailed > " + e.errorCode); // AdMob.ERROR_CODE_*
}

 function onAdLeftApp(e:AdMobEvents):void
{
	trace("onAdLeftApp > " + e.adType); // AdMob.AD_TYPE_*
}

 

 function onAdOpened(e:AdMobEvents):void
{
	trace("onAdOpened > " + e.adType); // AdMob.AD_TYPE_*
}
```

Could you please correct this code...i request you to dont send the demo.as code, because it is too big.
I am beginner so please correct my code.
Tell me the steps which i want to correct.
while opening apk..it showing you are using demo version of flashlab.

Hope i expect your positive reply.

**Comment by hadisn** [comment]
I have the same issue...

**Comment by myflashlab** [comment]
1. use the latest version of the ANE
2. make sure you are running on a real device not a simulator
3. make sure you have embedded the ANEs correctly in your project
4. in the error log you provided, I don't see any ANE related code!

**Comment by hadisn** [comment]
I am using latest version of the ANE.
When trying to publish it on real device i got this error: ---------------------------
Adobe Animate
---------------------------
Error creating files.

aapt tool failed:C:\Users\Hadis\AppData\Local\Temp\fa32ee20-ca5f-4c89-af78-f9c9651df8ed\AndroidManifest.xml:95: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

my as3 code:
`import com.myflashlab.air.extensions.admob.*;
import com.myflashlab.air.extensions.dependency.OverrideAir;

// initialize AdMob and pass in the Adobe AIR Stage and your AdmMob ApplicationCode
if(OverrideAir.os == OverrideAir.ANDROID) AdMob.init(stage, "ca-app-pub-9002001127208746~3709582175");
else if(OverrideAir.os == OverrideAir.IOS) AdMob.init(stage, "ca-app-pub-9002001127208746~3709582176");

// Add general listeners for the Ads
AdMob.api.addEventListener(AdMobEvents.AD_LOADED, 				onAdLoaded);

/*
	One thing you should remember about interstitial Ads, is that you should load them first,
	wait for them to be loaded, then show them when appropriate. For the best practice usage of
	interstitial Ads, read here: https://support.google.com/admob/answer/6066980?hl=en
*/

// The first step is to initialize a new interstitial Ad with your unitId that you have created in your Admob console.
AdMob.api.interstitial.init("ca-app-pub-9476398060240162/1457820116");

// then create a new Ad request just like how you did for the Banner Ads
var adRequest:AdRequest = new AdRequest();

// And then load it!
AdMob.api.interstitial.loadAd(adRequest);

// now, you must wait for the banner to load before you can show it.
function onAdLoaded(e:AdMobEvents):void
{
	if (e.adType == AdMob.AD_TYPE_INTERSTITIAL)
	{
		// Your Ad is ready to be shown. show it whenever you like!
		if(AdMob.api.interstitial.isLoaded)
		{
			AdMob.api.interstitial.show();
		}
	}
}`

**Comment by myflashlab** [comment]
Check your manifest file and make sure you have set it correctly. compare it with the sample file https://github.com/myflashlab/Admob-ANE/blob/master/AIR/Main-app.xml

And please consider opening a new ticket because your question is NOT similar to the question of the original user.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
