### ISSUE TITLE
Cant't compile  swc missed

### ISSUE THREAD

**Issue by gonzos978** [myflashlab/Admob-ANE#5]
I can't compile my app with admob dependencies. Look at image.
![screen shot 06-30-16 at 12 14 am](https://cloud.githubusercontent.com/assets/2334548/16470645/c5c47dde-3e57-11e6-8e24-cb7522eccff6.PNG)

**Comment by myflashlab** [comment]
usually you don't need swc files of ANEs, but tell me if we should really add them to the repository? before we find the time to update the repository, here is all the dependency latest .swc versions. Please do let us know why they are necessary. We have never used intelliJ IDE for compiling Air apps. hmm, I hope I'm not asking for too much but can you prepare and send us a very basic demo project in inteliJ which would compile to Android/iOS so maybe we can play around with it and better help other devs who might be using that IDE? Thanks.

[swc.zip](https://github.com/myflashlab/Admob-ANE/files/340766/swc.zip)

**Comment by DFABRIK** [comment]
Sorry for delay-just info: IntelliJ is OK, I'd just have wrong downloaded dependencies.Everything works well.
