### ISSUE TITLE
interstitial ads showing outside of the app environment

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/Admob-ANE#50]
Hi.

Google sent me letter:
> In a recent review of your account, our systems have detected interstitial ads showing outside of the app environment for your application, *** , with package ID air.com.***. Please note that this is a violation of Google Play and AdMob policies.
On November 19th, any apps in violation will be removed from Google Play and will require resubmission. Apps can be re-submitted with updated versions that resolve this and any other policy violations. Please note that repeated violations may result in additional enforcement such as app suspension.

I was very surprised, because my apps do not use interstitial ads, just rewarded video. 

this is code of AdMob initialization

```actionscript
        // initialize AdMob and pass in the Adobe Air Stage and your AdmMob ApplicationCode
        AdMob.init(Framework.stage, SettingsMobile.ADMOB_APP_ID);

        //AdMob.api.banner.init(getUnitId(AD_TYPE_BANNER), ApiBannerAds.BANNER);
        //AdMob.api.interstitial.init(getUnitId(AD_TYPE_INTERSTITIAL));

        // Add general listeners for the Ads
        AdMob.api.addEventListener(AdMobEvents.AD_CLOSED, onAdClosed);
        AdMob.api.addEventListener(AdMobEvents.AD_FAILED, onAdFailed);
        AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP, onAdLeftApp);
        AdMob.api.addEventListener(AdMobEvents.AD_LOADED, onAdLoaded);
        AdMob.api.addEventListener(AdMobEvents.AD_OPENED, onAdOpened);

        // listen to the banner Ad to get its final width/height in pixels so you can place it anywhere you like in your Air app
        AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);

        // listen to the RewardVideo Ad events
        AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_BEGIN_PLAYING, onRewardedVideoPlayingBegin);
        AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_END_PLAYING, onRewardedVideoPlayingEnd);
        AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_DELIVER_REWARD, onRewardedVideoDeliverReward);

```

What I will need to do to avoid suspension?

**Comment by myflashlab** [comment]
This is very interesting! I had a quick search and found this thread: https://www.reddit.com/r/androiddev/comments/9uons2/interstitial_ad_policy_violation/

The post was made yesterday, so this is something that Google is doing very recently. Please read there and see if you can relate?

**Comment by ikuprin** [comment]
Yeap. It is new. Some developers says that it can be related to trying initialize|preload|show ad in background.
As you can see in code I do not init interstitial, so maybe some code of ane doing this?

**Comment by myflashlab** [comment]
Definitely not! in ANE, if you are not initializing interstitial ads, ```new InterstitialAd(_activity)``` will not be called.

There must be another reason for this... :thinking:

**Comment by myflashlab** [comment]
some interesting points in the thread are: (you're not using interstitial ads to begin with! which makes things VERY suspicious/weird)

> Do you correctly preload the interstitial ad? Do you show it after an user action (tap on a button for example)?

> whats your CTR? Anything over like 5% usually makes them think you're doing something shady

I also noticed the following comment which seems very scary! can people really do that?! I don't think Google would allow that!
> Might be that someone extracted your Ad Ids and uses them somewhere else to wrack your business. Doable in mere minutes.

**Comment by myflashlab** [comment]
I'd suggest you to get in touch with Google and ask for more information... starting with the fact that you are not even initializing interstitial ads!

**Comment by ikuprin** [comment]
Wrote. Waiting for Google response.

**Comment by myflashlab** [comment]
Nice finding @ikuprin Can you prevent the load when the app is in background?
Normally, rewarded videos will be shown when their load finishes like the below sample.

```actionscript
private function onAdLoaded(e:AdMobEvents):void
{
	if (e.adType == AdMob.AD_TYPE_REWARDED_VIDEO)
	{
		// Your Ad is ready to be shown. show it whenever you like!
		if(AdMob.api.rewardedVideo.isReady)
		{
			AdMob.api.rewardedVideo.show();
		}
	}
}
```

But this is just a sample and you can change when to call ```AdMob.api.rewardedVideo.show();```. You may add another if clause and check if app is in foreground or not. and if it's not, don't show the ad.

**Comment by AlexUrrutia** [comment]
Try this:
```
function onAdLoaded(e:AdMobEvents):void {
            if (e.adType == AdMob.AD_TYPE_INTERSTITIAL) {
                trace("- INTERSTITIAL LOADED AND READY -");
            }
}

if app is not in background
some function():void{
AdMob.api.interstitial.isLoaded) {
               AdMob.api.interstitial.show();
}

```
**You should not call AdMob.api.interstitial.show(); inside onAdLoaded**

**Comment by ikuprin** [comment]
@AlexUrrutia 
I can prevent showing before it called. But I can't prevent showing from Action Script after it called - here is a problem.

**Comment by myflashlab** [comment]
@ikuprin like how @AlexUrrutia suggested, you should make sure your app is in foreground before calling the ```show()``` method.

Yet, there's a [dispose](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/admob/ApiRewardedVideo.html#dispose()) method for rewarded videos and a similar method for [iInterstitialAds](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/admob/ApiInterstitialAds.html#dispose())

**Comment by myflashlab** [comment]
You don't need to re-init the ANE but surely you should re-init the rewardedVideo and the interstitial ad after it is being disposed.

**Comment by ikuprin** [comment]
I do not see init method for rewardedVideo.

What about listeners? 
```

        AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_BEGIN_PLAYING, onRewardedVideoPlayingBegin);
        AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_END_PLAYING, onRewardedVideoPlayingEnd);
        AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_DELIVER_REWARD, onRewardedVideoDeliverReward);


```
Do I need to re-attach those after dispose?

**Comment by myflashlab** [comment]
oh, you're right actually. unlike the interstitial ads, the RewardedVideo API automatically calls init internally when any of the methods are called.

about listeners, please note that they are added when the ANE itself is being initialized. so you don't need to re-attach them.

let us know how does your tests go.

**Comment by ikuprin** [comment]
Dispose works as expected. But you can't simply listen to Event.DEACTIVATE, because showing of video deactivate application. So some crunch is needed. Thanks for help.

**Comment by myflashlab** [comment]
I see, let us do some tests and will update you a.s.a.p

**Comment by myflashlab** [comment]
Ok, we have two scenarios here:

A. When the RewardedVideo is playing and user takes the app to background: In this case, the video pauses automatically.

B. When video is still loading and before the ```AdMobEvents.AD_LOADED``` happens, user goes to background. When this happens and you have the ```AdMob.api.rewardedVideo.show();``` method in the onLoaded method (which is not a good idea as explained before), the video will bring up the app and plays the video: In this case, there's an easy fix. set a ```_isAppInBackground``` variable and save the state of the app if it's in foreground or background.

```actionscript
private function handleActivate(e:Event):void
{
	_isAppInBackground = false;
}

private function handleDeactivate(e:Event):void
{
	_isAppInBackground = true;
}
```

And play the video only when the app is in background:
```actionscript
private function onAdLoaded(e:AdMobEvents):void
{
	if(e.adType == AdMob.AD_TYPE_REWARDED_VIDEO)
	{
		if(_isAppInBackground)
		{
			trace("should not play the video when app is in background")
		}
		else
		{
			if(AdMob.api.rewardedVideo.isReady)
			{
				AdMob.api.rewardedVideo.show();
			}
		}
	}
}
```
Am I missing something here?

**Comment by ikuprin** [comment]
Yes. Missed.

Smth wrong with me ) I can't explain a problem ) Let's try another words...

Sometimes after! calling AdMob.api.rewardedVideo.show(); there is PAUSE before! video actually start playing. Sometimes this pause is several seconds. All this time application in foreground and user can hide application. But when video actually! starts - it's showing in foreground and after video closed - application in foreground without any user action.

So, my solution is:
```
Framework.addEventListener(Event.DEACTIVATE, disposeRewardedVideo);

      public function disposeRewardedVideo(e:Event = null):void {
        if (_disposeRewardedVideo) {
          AdMob.api.rewardedVideo.dispose();
        }
      }

    private function onAdLoaded(e:AdMobEvents):void {

      if (Framework.isStageDeactivated) {
        Debug.log("AdMobExtended::onAdLoaded > app in background. Displaying suppressed;");
        return;
      }

...
        if(AdMob.api.rewardedVideo.isReady) {
          _disposeRewardedVideo = false;
          setTimeout(function():void{_disposeRewardedVideo = true;}, 1000);
          AdMob.api.rewardedVideo.show();
        }
...
    }

```

Yeap. I know. Very bad code. But in this case all works as expected..

**Comment by ikuprin** [comment]
Right. If delay will be more than second, video will not starts.

**Comment by myflashlab** [comment]
@ikuprin I'm also curious about the Google email, did they accepted your modified app as a fix?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
