### ISSUE TITLE
Error after impliment and writing code

### ISSUE THREAD

**Issue by BAAKILI1987** [myflashlab/Admob-ANE#52]
What does mean that ?

 This ANE will not work unless you have added the other dependency ANEs
 or .frameworks to your project also. Please read the setup information
 and also check out the sample project on our repository to know what
 are the requirements for this ANE to work as expected

  how can i add other dependency ANEs  or frameworks ? :

and when i impliment and writing the code in first frame timeline (Animate CC)  does not debug and i make Error  :

ReferenceError: Error #1065: Variable onAdClosed is not defined
informations :  
- logiciel : Animate CC2017
- just Android Application.
 help me please !
 thanks

**Comment by myflashlab** [comment]
You asked the same questions a few minutes ago [here](https://github.com/myflashlab/Admob-ANE/issues/2#issuecomment-440686962) and I answered!

Here's a more detailed answer: Every ANE has an implementation instruction. the common implementations are explained in these videos: https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O

However, there are some specific instructions unique to every ANE. these are explained in our GitHub repository and wiki pages. have you checked out the wiki docs? https://github.com/myflashlab/Admob-ANE/wiki

ALL the information you need to implement this ANE into your project is provided in the wiki and the [sample project](https://github.com/myflashlab/Admob-ANE/tree/master/AIR)

About this: ```ReferenceError: Error #1065: Variable onAdClosed is not defined```:
This is just a function in our sample code! Why are you missing the information? Please Take your time and study the docs first!!! Let me know if you have more questions. I'd be happy to help

**Comment by BAAKILI1987** [comment]
i did all that you said me by stepsbut i cant solve this error (onAdclosed) 
(information : Iwrite the code in the first frame timeline ).
but debogation defailed (problem)
i imlpiment all common dependency and i copy the code 
i can t publish my application

**Comment by BAAKILI1987** [comment]
my code as that i write  is : 
import com.myflashlab.air.extensions.admob.*;
import com.myflashlab.air.extensions.dependency.OverrideAir;

// initialize AdMob and pass in the Adobe AIR Stage and your AdmMob ApplicationCode
AdMob.init(stage, "ca-app-pub-6998843331112417~7511480782");

AdMob.api.addEventListener(AdMobEvents.AD_CLOSED,onAdClosed);
AdMob.api.addEventListener(AdMobEvents.AD_FAILED,onAdFailed);
AdMob.api.addEventListener(AdMobEvents.AD_LEFT_APP,onAdLeftApp);
AdMob.api.addEventListener(AdMobEvents.AD_LOADED,onAdLoaded);
AdMob.api.addEventListener(AdMobEvents.AD_OPENED,onAdOpened);

function onAdClosed(e:AdMobEvents):void
{
	trace("onAdClosed > " + e.adType); // AdMob.AD_TYPE_*
}

function onAdFailed(e:AdMobEvents):void
{
	trace("onAdFailed > " + e.adType); // AdMob.AD_TYPE_*
	trace("onAdFailed > " + e.errorCode); // AdMob.ERROR_CODE_*
}

function onAdLeftApp(e:AdMobEvents):void
{
	trace("onAdLeftApp > " + e.adType); // AdMob.AD_TYPE_*
}


function onAdOpened(e:AdMobEvents):void
{
	trace("onAdOpened > " + e.adType);
}

AdMob.api.addEventListener(AdMobEvents.AD_LOADED,onAdLoaded);
AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED,onBannerAdSizeReceived);
AdMob.api.rewardedVideo.addEventListener(AdMobEvents.AD_DELIVER_REWARD, onDeliverReward);

var adRequest:AdRequest = new AdRequest();

AdMob.api.banner.init("ca-app-pub-6998843331112417/8632990762",ApiBannerAds.BANNER);
AdMob.api.interstitial.init("ca-app-pub-6998843331112417/5548620281");

AdMob.api.interstitial.loadAd(adRequest);
AdMob.api.banner.loadAd(adRequest);

function onAdLoaded(e:AdMobEvents):void
{
	trace("onAdLoaded > " + e.adType);
	
	if (e.adType == AdMob.AD_TYPE_BANNER)
	{
		AdMob.api.banner.x = stage.stageWidth / 2 - AdMob.api.banner.width / 2;
		AdMob.api.banner.y = stage.stageHeight / 2 - AdMob.api.banner.height / 2;
	}
	else if (e.adType == AdMob.AD_TYPE_INTERSTITIAL)
	{
		if(AdMob.api.interstitial.isLoaded)
		{
			AdMob.api.interstitial.show();
		}
	}
}

**Comment by myflashlab** [comment]
your code seems fine! You need to figure out what you have missed on your sample code tests. when AIR says ```Variable onAdClosed is not defined```, that means you have missed to declare the function. But I can see that you have declared it already. So, you must recheck your sample code. There's something wrong there. The error is not coming from the ANE to begin with!

**Comment by BAAKILI1987** [comment]
exactly Mr !
i check the code bu now it shows this error : 

it show TypeError : Error #1009: Cannot access a property or method of a null object reference.

can i ignore this error and i publish my application

**Comment by myflashlab** [comment]
Can you be more specific on ```Cannot access a property or method of a null object reference.```? is it the ANE instance? If so, that means the ANE is not implemented in your project correctly. Post your manifest .xml file here.

Another reason could be that you are testing on a simulator. don't. use a real device instead.

**Comment by BAAKILI1987** [comment]
thanks very much !!

<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/31.0">
  <id>Tamazgha</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel></versionLabel>
  <filename>Tamazgha</filename>
  <description/>
  <name>Tamazgha</name>
  <copyright/>
  <initialWindow>
    <content>Tamazgha.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    
    <renderMode>cpu</renderMode>
    <autoOrients>true</autoOrients></initialWindow>
  <icon>
    <image36x36>AppIconsForPublish/1.png</image36x36>
    <image48x48>AppIconsForPublish/2.png</image48x48>
    <image72x72>AppIconsForPublish/t3.png</image72x72>
    <image96x96>AppIconsForPublish/t4.png</image96x96>
    <image144x144>AppIconsForPublish/t5.png</image144x144>
    <image192x192>AppIconsForPublish/t6.png</image192x192>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
				
				<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="26" />
				                
				
			    <uses-permission android:name="android.permission.INTERNET"/>
				<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
				
				<application>
					
										
					<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
					
					
        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />

				</application>

			</manifest>
			
		]]></manifestAdditions>
    </android>
  <supportedLanguages>en zh nl fr it ko pl pt ru es sv tr</supportedLanguages>
  
  
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
  </extensions>
</application>

**Comment by BAAKILI1987** [comment]
exactly i test in a simulator !!!

my xml discriptoris : 

<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/31.0">
  <id>chamss</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel></versionLabel>
  <filename>chamss</filename>
  <description/>
  <name>hamss</name>
  <copyright/>
  <initialWindow>
    <content>chamss.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    
    <renderMode>cpu</renderMode>
    <autoOrients>true</autoOrients></initialWindow>
  <icon>
    <image36x36>AppIconsForPublish/1.png</image36x36>
    <image48x48>AppIconsForPublish/2.png</image48x48>
    <image72x72>AppIconsForPublish/t3.png</image72x72>
    <image96x96>AppIconsForPublish/t4.png</image96x96>
    <image144x144>AppIconsForPublish/t5.png</image144x144>
    <image192x192>AppIconsForPublish/t6.png</image192x192>
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
        <manifestAdditions><![CDATA[
			<manifest android:installLocation="auto">
				
				<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="26" />
				                
				
			    <uses-permission android:name="android.permission.INTERNET"/>
				<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
				
				<application>
					
										
					<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
					
					
        <activity
            android:name="com.google.android.gms.ads.AdActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />

				</application>

			</manifest>
			
		]]></manifestAdditions>
    </android>
  <supportedLanguages>en zh nl fr it ko pl pt ru es sv tr</supportedLanguages>
  
  
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.admob</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.arch</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.ads.lite</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport.customtabs</extensionID>
  </extensions>
</application>

**Comment by BAAKILI1987** [comment]
an other problem is when i impliment common dependency the file size increases (from 10 Mo  to 15Mo)

**Comment by myflashlab** [comment]
1. Run on  a real device not the simulator
2. You don't need to add .swc files! Just add the .ane files.

> an other problem is when i impliment common dependency the file size increases

You are adding Admob SDK to your app, you don't expect it to be 0 bytes, do you? The dependency ANEs are ensuring that the SDK is added to your app.

**Comment by BAAKILI1987** [comment]
nice and thanks for information !
WATH does mean "Admob SDK"  ?
i added just the Air SDK for api level 26.

**Comment by myflashlab** [comment]
Considering that this is no more an ANE related issue, I'll close it now. But, contact us through [this page](https://www.myflashlabs.com/contact/) and link back to this page so my colleagues will be able to assist you more from there.

So, the main problem you are facing is not to be familiar with coding ActionScript in separate .as files, right? The good news is that our ANEs do work on .as or timeline codes. So no worries about that. It's just that we are considering our users to be a little bit more familiar with .as. Anyhow, I am seeing two options here:

1. You may wish to spend a one our live session Skype/TeamViewer with us so we can teach you how to setup your project with .as files and how to implement ANEs in the most easiest way.
2. We could build a sample timeframe code FLA project for you!

Contact us via the link above and let us know which option do you prefer. Thanks.
