### ISSUE TITLE
firbase

### ISSUE THREAD

**Issue by BAAKILI1987** [myflashlab/Admob-ANE#55]
i want begin to use facebook for admob and  firbase analytique .
is there the firebase ane and facebook ane ?
where can i find it butit may be excellent and usefull correctly
thank you ?

**Comment by myflashlab** [comment]
You'll need [FirebaseCore](https://www.myflashlabs.com/product/firebase-air-native-extension/) then [Firebase Analytics](https://www.myflashlabs.com/product/analytics-firebase-air-native-extension/).

For Facebook, [here it is](https://www.myflashlabs.com/product/facebook-ane-adobe-air-native-extension/).

**NOTICE:** Please ask tech related question on Github ONLY. Thanks.

**Comment by BAAKILI1987** [comment]
what is the importance of facebook ANE ?

can i use firebase and facebook and admob anes in one application .

thanks

**Comment by myflashlab** [comment]
> what is the importance of facebook ANE ?

Well, you said you want to use it! I'm not sure I understand what you mean.

> can i use firebase analytique without using Firebase Core ?

No, Of course not. This is clearly mentioned in our website and docs.

> can i use firebase and facebook and admob anes in one application .

YES! You can use ALL our ANEs in one application!
