### ISSUE TITLE
Android banner is not shown

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/Admob-ANE#56]
Interstitial and rewarded ads work fine, but banner is not shown.
`AdMobEvents.AD_LOADED` - success
`AdMobEvents.SIZE_MEASURED` - returns 0 width and 0 height.
I tried different types of banner
`ApiBannerAds.BANNER`, `SMART_BANNER_LANDSCAPE` ant etc,

**Comment by AlexUrrutia** [comment]
**Try this:**
```
AdMob.api.banner.addEventListener(AdMobEvents.SIZE_MEASURED, onBannerAdSizeReceived);
private function onBannerAdSizeReceived(e:AdMobEvents):void
    {
        AdMob.api.banner.loadAd(adRequest);
    }
```

**Comment by CrazyFlasher** [comment]
Cool. Thanks helped! Thanks
