### ISSUE TITLE
Anyone Please Help, admob ad not shown by using orginal ID

### ISSUE THREAD

**Issue by sahanasalim** [myflashlab/Admob-ANE#58]
I used lot of ANE for admob , im using flash cc and coding done by AS3(Action Script 3).
I can successfully run code & take Apk for Android devices, And I got test ad after run my apk in android devices.
When i use orginal ad ID i didnt get any ad i got message like Failed to load interstitial ad from the other side.
i used flash animate 2017 also but result is same.
i dont get any ad by using orginal id, this is happend some days before. my All Android live Apps in playstore are working and this issues happens when i take new apk for update game or new game apks.PLEASE HELP ANYONE....

**Comment by myflashlab** [comment]
can you send us your .apk file so we can install and check here?

**Comment by ashmyy** [comment]
here is the .apk you can install and check
https://play.google.com/store/apps/details?id=air.com.infocom.blackjack
