### ISSUE TITLE
Banner not appearing in App

### ISSUE THREAD

**Issue by leossmith** [myflashlab/Admob-ANE#7]
I am trying to add a banner on my Flex app without any luck. I don't get an error, but i can't see the banner. Could this be under the flex layer? 

After initialising it, if i try to do it all over again, it fails, so it looks like it works, although i don't see it ony my device.

I am testing on android 6.0.1

**Comment by myflashlab** [comment]
1. does your same code work on iOS?
2. try re-positioning the banner by changing the x/y values and see if it appears?

**Comment by myflashlab** [comment]
Would you please update us about this issue?
