### ISSUE TITLE
importing the extension

### ISSUE THREAD

**Issue by MamdouhSar** [myflashlab/Admob-ANE#8]
Hello,

I have included the AdMob ANE I have bought to the project, however I cannot import it to the project. it gives me an error when using "import com.myflashlab.air.extensions.admob".

**Comment by myflashlab** [comment]
Would you please tell us what error message you are receiving? and on what platform? Also make sure you have watched these videos https://www.youtube.com/watch?v=Oubsb_3F3ec&list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O which may help you in the process of implementing ANEs into your project.

**Comment by MamdouhSar** [comment]
Thank you for answering, It works now. I've had some errors in the code.
