### ISSUE TITLE
Error code 3

### ISSUE THREAD

**Issue by MamdouhSar** [myflashlab/Admob-ANE#9]
Hello,
I'm trying to add a banner ad in my app, however whenever I debug on my phone it says error code 3. What does that mean? and if you could tell me how can I fix this I'd be grateful.

**Comment by myflashlab** [comment]
You might find this link helpful: http://stackoverflow.com/a/33712905/247658

> As per the Documentation you are getting the following error code:

    public static final int ERROR_CODE_NO_FILL

    The ad request was successful, but no ad was returned due to lack of ad inventory.

    Constant Value: 3

>Based on the post onFailedToReceiveAd - Ad request successful, but no ad returned due to lack of ad inventory when using admob with adwhirl:

    If you are getting this error, then your code is correct. The issue is that AdMob does not always have an ad to return for every request. This may happen particularly if you have just registered your AdMob publisher ID, as it takes some time and multiple requests before the new ID starts returning ads.

    Another reason your fill rate may be low is that you don't have AdSense backfill enabled, or you have filtered out some ads. Check your app settings to see if that is the case.

**Comment by myflashlab** [comment]
If the problem is fixed, would you update this ticket?

**Comment by MamdouhSar** [comment]
Yep, it's fixed.
Thank you
